/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.commons.file.manager.ExportedFileManager;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.tools.api.core.annotations.MapTo;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.wavemaker.when_to_work.when2work.Category;
import com.wavemaker.when_to_work.when2work.GroupCat;
import com.wavemaker.when_to_work.when2work.ScheduledEmployee;
import com.wavemaker.when_to_work.when2work.service.CategoryService;


/**
 * Controller object for domain model class Category.
 * @see Category
 */
@RestController("when2work.CategoryController")
@Api(value = "CategoryController", description = "Exposes APIs to work with Category resource.")
@RequestMapping("/when2work/Category")
public class CategoryController {

    private static final Logger LOGGER = LoggerFactory.getLogger(CategoryController.class);

    @Autowired
	@Qualifier("when2work.CategoryService")
	private CategoryService categoryService;

	@Autowired
	private ExportedFileManager exportedFileManager;

	@ApiOperation(value = "Creates a new Category instance.")
    @PostMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Category createCategory(@RequestBody Category category) {
		LOGGER.debug("Create Category with information: {}" , category);

		category = categoryService.create(category);
		LOGGER.debug("Created Category with information: {}" , category);

	    return category;
	}

    @ApiOperation(value = "Returns the Category instance associated with the given id.")
    @GetMapping(value = "/{categoryId:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Category getCategory(@PathVariable("categoryId") Integer categoryId) {
        LOGGER.debug("Getting Category with id: {}" , categoryId);

        Category foundCategory = categoryService.getById(categoryId);
        LOGGER.debug("Category details with id: {}" , foundCategory);

        return foundCategory;
    }

    @ApiOperation(value = "Updates the Category instance associated with the given id.")
    @PutMapping(value = "/{categoryId:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Category editCategory(@PathVariable("categoryId") Integer categoryId, @RequestBody Category category) {
        LOGGER.debug("Editing Category with id: {}" , category.getCategoryId());

        category.setCategoryId(categoryId);
        category = categoryService.update(category);
        LOGGER.debug("Category details with id: {}" , category);

        return category;
    }
    
    @ApiOperation(value = "Partially updates the Category instance associated with the given id.")
    @PatchMapping(value = "/{categoryId:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Category patchCategory(@PathVariable("categoryId") Integer categoryId, @RequestBody @MapTo(Category.class) Map<String, Object> categoryPatch) {
        LOGGER.debug("Partially updating Category with id: {}" , categoryId);

        Category category = categoryService.partialUpdate(categoryId, categoryPatch);
        LOGGER.debug("Category details after partial update: {}" , category);

        return category;
    }

    @ApiOperation(value = "Deletes the Category instance associated with the given id.")
    @DeleteMapping(value = "/{categoryId:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteCategory(@PathVariable("categoryId") Integer categoryId) {
        LOGGER.debug("Deleting Category with id: {}" , categoryId);

        Category deletedCategory = categoryService.delete(categoryId);

        return deletedCategory != null;
    }

    /**
     * @deprecated Use {@link #findCategories(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of Category instances matching the search criteria.")
    @PostMapping(value = "/search")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Category> searchCategoriesByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering Categories list by query filter:{}", (Object) queryFilters);
        return categoryService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Category instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @GetMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Category> findCategories(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Categories list by filter:", query);
        return categoryService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Category instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @PostMapping(value="/filter", consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Category> filterCategories(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Categories list by filter", query);
        return categoryService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param.")
    @GetMapping(value = "/export/{exportType}", produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportCategories(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return categoryService.export(exportType, query, pageable);
    }

    @ApiOperation(value = "Returns a URL to download a file for the data matching the optional query (q) request param and the required fields provided in the Export Options.") 
    @PostMapping(value = "/export", consumes = "application/json")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportCategoriesAndGetURL(@RequestBody DataExportOptions exportOptions, Pageable pageable) {
        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = Category.class.getSimpleName();
        }
        exportedFileName += exportOptions.getExportType().getExtension();
        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName, outputStream -> categoryService.export(exportOptions, pageable, outputStream));
        return new StringWrapper(exportedUrl);
    }

	@ApiOperation(value = "Returns the total count of Category instances matching the optional query (q) request param.")
	@GetMapping(value = "/count")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countCategories( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting Categories");
		return categoryService.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@PostMapping(value = "/aggregations")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getCategoryAggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return categoryService.getAggregatedValues(aggregationInfo, pageable);
    }

    @GetMapping(value="/{categoryId:.+}/groupCats")
    @ApiOperation(value = "Gets the groupCats instance associated with the given id.")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<GroupCat> findAssociatedGroupCats(@PathVariable("categoryId") Integer categoryId, Pageable pageable) {

        LOGGER.debug("Fetching all associated groupCats");
        return categoryService.findAssociatedGroupCats(categoryId, pageable);
    }

    @GetMapping(value="/{categoryId:.+}/scheduledEmployees")
    @ApiOperation(value = "Gets the scheduledEmployees instance associated with the given id.")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<ScheduledEmployee> findAssociatedScheduledEmployees(@PathVariable("categoryId") Integer categoryId, Pageable pageable) {

        LOGGER.debug("Fetching all associated scheduledEmployees");
        return categoryService.findAssociatedScheduledEmployees(categoryId, pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service CategoryService instance
	 */
	protected void setCategoryService(CategoryService service) {
		this.categoryService = service;
	}

}
