/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.commons.file.manager.ExportedFileManager;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.tools.api.core.annotations.MapTo;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.wavemaker.when_to_work.when2work.CatGroup;
import com.wavemaker.when_to_work.when2work.GroupCat;
import com.wavemaker.when_to_work.when2work.service.CatGroupService;


/**
 * Controller object for domain model class CatGroup.
 * @see CatGroup
 */
@RestController("when2work.CatGroupController")
@Api(value = "CatGroupController", description = "Exposes APIs to work with CatGroup resource.")
@RequestMapping("/when2work/CatGroup")
public class CatGroupController {

    private static final Logger LOGGER = LoggerFactory.getLogger(CatGroupController.class);

    @Autowired
	@Qualifier("when2work.CatGroupService")
	private CatGroupService catGroupService;

	@Autowired
	private ExportedFileManager exportedFileManager;

	@ApiOperation(value = "Creates a new CatGroup instance.")
    @PostMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public CatGroup createCatGroup(@RequestBody CatGroup catGroup) {
		LOGGER.debug("Create CatGroup with information: {}" , catGroup);

		catGroup = catGroupService.create(catGroup);
		LOGGER.debug("Created CatGroup with information: {}" , catGroup);

	    return catGroup;
	}

    @ApiOperation(value = "Returns the CatGroup instance associated with the given id.")
    @GetMapping(value = "/{groupId:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public CatGroup getCatGroup(@PathVariable("groupId") Integer groupId) {
        LOGGER.debug("Getting CatGroup with id: {}" , groupId);

        CatGroup foundCatGroup = catGroupService.getById(groupId);
        LOGGER.debug("CatGroup details with id: {}" , foundCatGroup);

        return foundCatGroup;
    }

    @ApiOperation(value = "Updates the CatGroup instance associated with the given id.")
    @PutMapping(value = "/{groupId:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public CatGroup editCatGroup(@PathVariable("groupId") Integer groupId, @RequestBody CatGroup catGroup) {
        LOGGER.debug("Editing CatGroup with id: {}" , catGroup.getGroupId());

        catGroup.setGroupId(groupId);
        catGroup = catGroupService.update(catGroup);
        LOGGER.debug("CatGroup details with id: {}" , catGroup);

        return catGroup;
    }
    
    @ApiOperation(value = "Partially updates the CatGroup instance associated with the given id.")
    @PatchMapping(value = "/{groupId:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public CatGroup patchCatGroup(@PathVariable("groupId") Integer groupId, @RequestBody @MapTo(CatGroup.class) Map<String, Object> catGroupPatch) {
        LOGGER.debug("Partially updating CatGroup with id: {}" , groupId);

        CatGroup catGroup = catGroupService.partialUpdate(groupId, catGroupPatch);
        LOGGER.debug("CatGroup details after partial update: {}" , catGroup);

        return catGroup;
    }

    @ApiOperation(value = "Deletes the CatGroup instance associated with the given id.")
    @DeleteMapping(value = "/{groupId:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteCatGroup(@PathVariable("groupId") Integer groupId) {
        LOGGER.debug("Deleting CatGroup with id: {}" , groupId);

        CatGroup deletedCatGroup = catGroupService.delete(groupId);

        return deletedCatGroup != null;
    }

    /**
     * @deprecated Use {@link #findCatGroups(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of CatGroup instances matching the search criteria.")
    @PostMapping(value = "/search")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<CatGroup> searchCatGroupsByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering CatGroups list by query filter:{}", (Object) queryFilters);
        return catGroupService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of CatGroup instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @GetMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<CatGroup> findCatGroups(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering CatGroups list by filter:", query);
        return catGroupService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of CatGroup instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @PostMapping(value="/filter", consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<CatGroup> filterCatGroups(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering CatGroups list by filter", query);
        return catGroupService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param.")
    @GetMapping(value = "/export/{exportType}", produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportCatGroups(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return catGroupService.export(exportType, query, pageable);
    }

    @ApiOperation(value = "Returns a URL to download a file for the data matching the optional query (q) request param and the required fields provided in the Export Options.") 
    @PostMapping(value = "/export", consumes = "application/json")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportCatGroupsAndGetURL(@RequestBody DataExportOptions exportOptions, Pageable pageable) {
        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = CatGroup.class.getSimpleName();
        }
        exportedFileName += exportOptions.getExportType().getExtension();
        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName, outputStream -> catGroupService.export(exportOptions, pageable, outputStream));
        return new StringWrapper(exportedUrl);
    }

	@ApiOperation(value = "Returns the total count of CatGroup instances matching the optional query (q) request param.")
	@GetMapping(value = "/count")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countCatGroups( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting CatGroups");
		return catGroupService.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@PostMapping(value = "/aggregations")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getCatGroupAggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return catGroupService.getAggregatedValues(aggregationInfo, pageable);
    }

    @GetMapping(value="/{groupId:.+}/groupCats")
    @ApiOperation(value = "Gets the groupCats instance associated with the given id.")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<GroupCat> findAssociatedGroupCats(@PathVariable("groupId") Integer groupId, Pageable pageable) {

        LOGGER.debug("Fetching all associated groupCats");
        return catGroupService.findAssociatedGroupCats(groupId, pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service CatGroupService instance
	 */
	protected void setCatGroupService(CatGroupService service) {
		this.catGroupService = service;
	}

}
