/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.commons.file.manager.ExportedFileManager;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.tools.api.core.annotations.MapTo;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.wavemaker.when_to_work.when2work.EmployeePhone;
import com.wavemaker.when_to_work.when2work.EmployeePhoneId;
import com.wavemaker.when_to_work.when2work.service.EmployeePhoneService;


/**
 * Controller object for domain model class EmployeePhone.
 * @see EmployeePhone
 */
@RestController("when2work.EmployeePhoneController")
@Api(value = "EmployeePhoneController", description = "Exposes APIs to work with EmployeePhone resource.")
@RequestMapping("/when2work/EmployeePhone")
public class EmployeePhoneController {

    private static final Logger LOGGER = LoggerFactory.getLogger(EmployeePhoneController.class);

    @Autowired
	@Qualifier("when2work.EmployeePhoneService")
	private EmployeePhoneService employeePhoneService;

	@Autowired
	private ExportedFileManager exportedFileManager;

	@ApiOperation(value = "Creates a new EmployeePhone instance.")
    @PostMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public EmployeePhone createEmployeePhone(@RequestBody EmployeePhone employeePhone) {
		LOGGER.debug("Create EmployeePhone with information: {}" , employeePhone);

		employeePhone = employeePhoneService.create(employeePhone);
		LOGGER.debug("Created EmployeePhone with information: {}" , employeePhone);

	    return employeePhone;
	}

    @ApiOperation(value = "Returns the EmployeePhone instance associated with the given composite-id.")
    @GetMapping(value = "/composite-id")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public EmployeePhone getEmployeePhone(@RequestParam("employeeId") Integer employeeId, @RequestParam("sortOrder") Integer sortOrder) {

        EmployeePhoneId employeephoneId = new EmployeePhoneId();
        employeephoneId.setEmployeeId(employeeId);
        employeephoneId.setSortOrder(sortOrder);

        LOGGER.debug("Getting EmployeePhone with id: {}" , employeephoneId);
        EmployeePhone employeePhone = employeePhoneService.getById(employeephoneId);
        LOGGER.debug("EmployeePhone details with id: {}" , employeePhone);

        return employeePhone;
    }



    @ApiOperation(value = "Updates the EmployeePhone instance associated with the given composite-id.")
    @PutMapping(value = "/composite-id")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public EmployeePhone editEmployeePhone(@RequestParam("employeeId") Integer employeeId, @RequestParam("sortOrder") Integer sortOrder, @RequestBody EmployeePhone employeePhone) {

        employeePhone.setEmployeeId(employeeId);
        employeePhone.setSortOrder(sortOrder);

        LOGGER.debug("EmployeePhone details with id is updated with: {}" , employeePhone);

        return employeePhoneService.update(employeePhone);
    }

	@ApiOperation(value = "Partially updates the  EmployeePhone instance associated with the given composite-id.")
	@PatchMapping(value = "/composite-id")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public EmployeePhone patchEmployeePhone(@RequestParam("employeeId") Integer employeeId, @RequestParam("sortOrder") Integer sortOrder, @RequestBody @MapTo(EmployeePhone.class) Map<String, Object> employeePhonePatch) {

        EmployeePhoneId employeephoneId = new EmployeePhoneId();
        employeephoneId.setEmployeeId(employeeId);
        employeephoneId.setSortOrder(sortOrder);
        LOGGER.debug("Partially updating EmployeePhone with id: {}" , employeephoneId);

        EmployeePhone employeePhone = employeePhoneService.partialUpdate(employeephoneId, employeePhonePatch);
        LOGGER.debug("EmployeePhone details after partial update: {}" , employeePhone);

        return employeePhone;
    }


    @ApiOperation(value = "Deletes the EmployeePhone instance associated with the given composite-id.")
    @DeleteMapping(value = "/composite-id")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteEmployeePhone(@RequestParam("employeeId") Integer employeeId, @RequestParam("sortOrder") Integer sortOrder) {

        EmployeePhoneId employeephoneId = new EmployeePhoneId();
        employeephoneId.setEmployeeId(employeeId);
        employeephoneId.setSortOrder(sortOrder);

        LOGGER.debug("Deleting EmployeePhone with id: {}" , employeephoneId);
        EmployeePhone employeePhone = employeePhoneService.delete(employeephoneId);

        return employeePhone != null;
    }


    /**
     * @deprecated Use {@link #findEmployeePhones(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of EmployeePhone instances matching the search criteria.")
    @PostMapping(value = "/search")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<EmployeePhone> searchEmployeePhonesByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering EmployeePhones list by query filter:{}", (Object) queryFilters);
        return employeePhoneService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of EmployeePhone instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @GetMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<EmployeePhone> findEmployeePhones(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering EmployeePhones list by filter:", query);
        return employeePhoneService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of EmployeePhone instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @PostMapping(value="/filter", consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<EmployeePhone> filterEmployeePhones(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering EmployeePhones list by filter", query);
        return employeePhoneService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param.")
    @GetMapping(value = "/export/{exportType}", produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportEmployeePhones(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return employeePhoneService.export(exportType, query, pageable);
    }

    @ApiOperation(value = "Returns a URL to download a file for the data matching the optional query (q) request param and the required fields provided in the Export Options.") 
    @PostMapping(value = "/export", consumes = "application/json")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportEmployeePhonesAndGetURL(@RequestBody DataExportOptions exportOptions, Pageable pageable) {
        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = EmployeePhone.class.getSimpleName();
        }
        exportedFileName += exportOptions.getExportType().getExtension();
        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName, outputStream -> employeePhoneService.export(exportOptions, pageable, outputStream));
        return new StringWrapper(exportedUrl);
    }

	@ApiOperation(value = "Returns the total count of EmployeePhone instances matching the optional query (q) request param.")
	@GetMapping(value = "/count")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countEmployeePhones( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting EmployeePhones");
		return employeePhoneService.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@PostMapping(value = "/aggregations")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getEmployeePhoneAggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return employeePhoneService.getAggregatedValues(aggregationInfo, pageable);
    }


    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service EmployeePhoneService instance
	 */
	protected void setEmployeePhoneService(EmployeePhoneService service) {
		this.employeePhoneService = service;
	}

}
