/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.commons.file.manager.ExportedFileManager;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.tools.api.core.annotations.MapTo;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.wavemaker.when_to_work.when2work.GroupSkill;
import com.wavemaker.when_to_work.when2work.GroupSkillId;
import com.wavemaker.when_to_work.when2work.service.GroupSkillService;


/**
 * Controller object for domain model class GroupSkill.
 * @see GroupSkill
 */
@RestController("when2work.GroupSkillController")
@Api(value = "GroupSkillController", description = "Exposes APIs to work with GroupSkill resource.")
@RequestMapping("/when2work/GroupSkill")
public class GroupSkillController {

    private static final Logger LOGGER = LoggerFactory.getLogger(GroupSkillController.class);

    @Autowired
	@Qualifier("when2work.GroupSkillService")
	private GroupSkillService groupSkillService;

	@Autowired
	private ExportedFileManager exportedFileManager;

	@ApiOperation(value = "Creates a new GroupSkill instance.")
    @PostMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public GroupSkill createGroupSkill(@RequestBody GroupSkill groupSkill) {
		LOGGER.debug("Create GroupSkill with information: {}" , groupSkill);

		groupSkill = groupSkillService.create(groupSkill);
		LOGGER.debug("Created GroupSkill with information: {}" , groupSkill);

	    return groupSkill;
	}

    @ApiOperation(value = "Returns the GroupSkill instance associated with the given composite-id.")
    @GetMapping(value = "/composite-id")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public GroupSkill getGroupSkill(@RequestParam("groupId") Integer groupId, @RequestParam("skillId") Integer skillId) {

        GroupSkillId groupskillId = new GroupSkillId();
        groupskillId.setGroupId(groupId);
        groupskillId.setSkillId(skillId);

        LOGGER.debug("Getting GroupSkill with id: {}" , groupskillId);
        GroupSkill groupSkill = groupSkillService.getById(groupskillId);
        LOGGER.debug("GroupSkill details with id: {}" , groupSkill);

        return groupSkill;
    }



    @ApiOperation(value = "Updates the GroupSkill instance associated with the given composite-id.")
    @PutMapping(value = "/composite-id")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public GroupSkill editGroupSkill(@RequestParam("groupId") Integer groupId, @RequestParam("skillId") Integer skillId, @RequestBody GroupSkill groupSkill) {

        groupSkill.setGroupId(groupId);
        groupSkill.setSkillId(skillId);

        LOGGER.debug("GroupSkill details with id is updated with: {}" , groupSkill);

        return groupSkillService.update(groupSkill);
    }

	@ApiOperation(value = "Partially updates the  GroupSkill instance associated with the given composite-id.")
	@PatchMapping(value = "/composite-id")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public GroupSkill patchGroupSkill(@RequestParam("groupId") Integer groupId, @RequestParam("skillId") Integer skillId, @RequestBody @MapTo(GroupSkill.class) Map<String, Object> groupSkillPatch) {

        GroupSkillId groupskillId = new GroupSkillId();
        groupskillId.setGroupId(groupId);
        groupskillId.setSkillId(skillId);
        LOGGER.debug("Partially updating GroupSkill with id: {}" , groupskillId);

        GroupSkill groupSkill = groupSkillService.partialUpdate(groupskillId, groupSkillPatch);
        LOGGER.debug("GroupSkill details after partial update: {}" , groupSkill);

        return groupSkill;
    }


    @ApiOperation(value = "Deletes the GroupSkill instance associated with the given composite-id.")
    @DeleteMapping(value = "/composite-id")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteGroupSkill(@RequestParam("groupId") Integer groupId, @RequestParam("skillId") Integer skillId) {

        GroupSkillId groupskillId = new GroupSkillId();
        groupskillId.setGroupId(groupId);
        groupskillId.setSkillId(skillId);

        LOGGER.debug("Deleting GroupSkill with id: {}" , groupskillId);
        GroupSkill groupSkill = groupSkillService.delete(groupskillId);

        return groupSkill != null;
    }


    /**
     * @deprecated Use {@link #findGroupSkills(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of GroupSkill instances matching the search criteria.")
    @PostMapping(value = "/search")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<GroupSkill> searchGroupSkillsByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering GroupSkills list by query filter:{}", (Object) queryFilters);
        return groupSkillService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of GroupSkill instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @GetMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<GroupSkill> findGroupSkills(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering GroupSkills list by filter:", query);
        return groupSkillService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of GroupSkill instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @PostMapping(value="/filter", consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<GroupSkill> filterGroupSkills(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering GroupSkills list by filter", query);
        return groupSkillService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param.")
    @GetMapping(value = "/export/{exportType}", produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportGroupSkills(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return groupSkillService.export(exportType, query, pageable);
    }

    @ApiOperation(value = "Returns a URL to download a file for the data matching the optional query (q) request param and the required fields provided in the Export Options.") 
    @PostMapping(value = "/export", consumes = "application/json")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportGroupSkillsAndGetURL(@RequestBody DataExportOptions exportOptions, Pageable pageable) {
        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = GroupSkill.class.getSimpleName();
        }
        exportedFileName += exportOptions.getExportType().getExtension();
        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName, outputStream -> groupSkillService.export(exportOptions, pageable, outputStream));
        return new StringWrapper(exportedUrl);
    }

	@ApiOperation(value = "Returns the total count of GroupSkill instances matching the optional query (q) request param.")
	@GetMapping(value = "/count")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countGroupSkills( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting GroupSkills");
		return groupSkillService.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@PostMapping(value = "/aggregations")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getGroupSkillAggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return groupSkillService.getAggregatedValues(aggregationInfo, pageable);
    }


    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service GroupSkillService instance
	 */
	protected void setGroupSkillService(GroupSkillService service) {
		this.groupSkillService = service;
	}

}
