/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.commons.file.manager.ExportedFileManager;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.tools.api.core.annotations.MapTo;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.wavemaker.when_to_work.when2work.GroupCat;
import com.wavemaker.when_to_work.when2work.GroupCatId;
import com.wavemaker.when_to_work.when2work.service.GroupCatService;


/**
 * Controller object for domain model class GroupCat.
 * @see GroupCat
 */
@RestController("when2work.GroupCatController")
@Api(value = "GroupCatController", description = "Exposes APIs to work with GroupCat resource.")
@RequestMapping("/when2work/GroupCat")
public class GroupCatController {

    private static final Logger LOGGER = LoggerFactory.getLogger(GroupCatController.class);

    @Autowired
	@Qualifier("when2work.GroupCatService")
	private GroupCatService groupCatService;

	@Autowired
	private ExportedFileManager exportedFileManager;

	@ApiOperation(value = "Creates a new GroupCat instance.")
    @PostMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public GroupCat createGroupCat(@RequestBody GroupCat groupCat) {
		LOGGER.debug("Create GroupCat with information: {}" , groupCat);

		groupCat = groupCatService.create(groupCat);
		LOGGER.debug("Created GroupCat with information: {}" , groupCat);

	    return groupCat;
	}

    @ApiOperation(value = "Returns the GroupCat instance associated with the given composite-id.")
    @GetMapping(value = "/composite-id")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public GroupCat getGroupCat(@RequestParam("groupId") Integer groupId, @RequestParam("catId") Integer catId) {

        GroupCatId groupcatId = new GroupCatId();
        groupcatId.setGroupId(groupId);
        groupcatId.setCatId(catId);

        LOGGER.debug("Getting GroupCat with id: {}" , groupcatId);
        GroupCat groupCat = groupCatService.getById(groupcatId);
        LOGGER.debug("GroupCat details with id: {}" , groupCat);

        return groupCat;
    }



    @ApiOperation(value = "Updates the GroupCat instance associated with the given composite-id.")
    @PutMapping(value = "/composite-id")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public GroupCat editGroupCat(@RequestParam("groupId") Integer groupId, @RequestParam("catId") Integer catId, @RequestBody GroupCat groupCat) {

        groupCat.setGroupId(groupId);
        groupCat.setCatId(catId);

        LOGGER.debug("GroupCat details with id is updated with: {}" , groupCat);

        return groupCatService.update(groupCat);
    }

	@ApiOperation(value = "Partially updates the  GroupCat instance associated with the given composite-id.")
	@PatchMapping(value = "/composite-id")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public GroupCat patchGroupCat(@RequestParam("groupId") Integer groupId, @RequestParam("catId") Integer catId, @RequestBody @MapTo(GroupCat.class) Map<String, Object> groupCatPatch) {

        GroupCatId groupcatId = new GroupCatId();
        groupcatId.setGroupId(groupId);
        groupcatId.setCatId(catId);
        LOGGER.debug("Partially updating GroupCat with id: {}" , groupcatId);

        GroupCat groupCat = groupCatService.partialUpdate(groupcatId, groupCatPatch);
        LOGGER.debug("GroupCat details after partial update: {}" , groupCat);

        return groupCat;
    }


    @ApiOperation(value = "Deletes the GroupCat instance associated with the given composite-id.")
    @DeleteMapping(value = "/composite-id")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteGroupCat(@RequestParam("groupId") Integer groupId, @RequestParam("catId") Integer catId) {

        GroupCatId groupcatId = new GroupCatId();
        groupcatId.setGroupId(groupId);
        groupcatId.setCatId(catId);

        LOGGER.debug("Deleting GroupCat with id: {}" , groupcatId);
        GroupCat groupCat = groupCatService.delete(groupcatId);

        return groupCat != null;
    }


    /**
     * @deprecated Use {@link #findGroupCats(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of GroupCat instances matching the search criteria.")
    @PostMapping(value = "/search")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<GroupCat> searchGroupCatsByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering GroupCats list by query filter:{}", (Object) queryFilters);
        return groupCatService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of GroupCat instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @GetMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<GroupCat> findGroupCats(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering GroupCats list by filter:", query);
        return groupCatService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of GroupCat instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @PostMapping(value="/filter", consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<GroupCat> filterGroupCats(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering GroupCats list by filter", query);
        return groupCatService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param.")
    @GetMapping(value = "/export/{exportType}", produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportGroupCats(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return groupCatService.export(exportType, query, pageable);
    }

    @ApiOperation(value = "Returns a URL to download a file for the data matching the optional query (q) request param and the required fields provided in the Export Options.") 
    @PostMapping(value = "/export", consumes = "application/json")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportGroupCatsAndGetURL(@RequestBody DataExportOptions exportOptions, Pageable pageable) {
        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = GroupCat.class.getSimpleName();
        }
        exportedFileName += exportOptions.getExportType().getExtension();
        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName, outputStream -> groupCatService.export(exportOptions, pageable, outputStream));
        return new StringWrapper(exportedUrl);
    }

	@ApiOperation(value = "Returns the total count of GroupCat instances matching the optional query (q) request param.")
	@GetMapping(value = "/count")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countGroupCats( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting GroupCats");
		return groupCatService.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@PostMapping(value = "/aggregations")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getGroupCatAggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return groupCatService.getAggregatedValues(aggregationInfo, pageable);
    }


    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service GroupCatService instance
	 */
	protected void setGroupCatService(GroupCatService service) {
		this.groupCatService = service;
	}

}
