/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.commons.file.manager.ExportedFileManager;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.tools.api.core.annotations.MapTo;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.wavemaker.when_to_work.when2work.Schedule;
import com.wavemaker.when_to_work.when2work.ScheduledEmployee;
import com.wavemaker.when_to_work.when2work.service.ScheduleService;


/**
 * Controller object for domain model class Schedule.
 * @see Schedule
 */
@RestController("when2work.ScheduleController")
@Api(value = "ScheduleController", description = "Exposes APIs to work with Schedule resource.")
@RequestMapping("/when2work/Schedule")
public class ScheduleController {

    private static final Logger LOGGER = LoggerFactory.getLogger(ScheduleController.class);

    @Autowired
	@Qualifier("when2work.ScheduleService")
	private ScheduleService scheduleService;

	@Autowired
	private ExportedFileManager exportedFileManager;

	@ApiOperation(value = "Creates a new Schedule instance.")
    @PostMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Schedule createSchedule(@RequestBody Schedule schedule) {
		LOGGER.debug("Create Schedule with information: {}" , schedule);

		schedule = scheduleService.create(schedule);
		LOGGER.debug("Created Schedule with information: {}" , schedule);

	    return schedule;
	}

    @ApiOperation(value = "Returns the Schedule instance associated with the given id.")
    @GetMapping(value = "/{scheduleId:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Schedule getSchedule(@PathVariable("scheduleId") Integer scheduleId) {
        LOGGER.debug("Getting Schedule with id: {}" , scheduleId);

        Schedule foundSchedule = scheduleService.getById(scheduleId);
        LOGGER.debug("Schedule details with id: {}" , foundSchedule);

        return foundSchedule;
    }

    @ApiOperation(value = "Updates the Schedule instance associated with the given id.")
    @PutMapping(value = "/{scheduleId:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Schedule editSchedule(@PathVariable("scheduleId") Integer scheduleId, @RequestBody Schedule schedule) {
        LOGGER.debug("Editing Schedule with id: {}" , schedule.getScheduleId());

        schedule.setScheduleId(scheduleId);
        schedule = scheduleService.update(schedule);
        LOGGER.debug("Schedule details with id: {}" , schedule);

        return schedule;
    }
    
    @ApiOperation(value = "Partially updates the Schedule instance associated with the given id.")
    @PatchMapping(value = "/{scheduleId:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Schedule patchSchedule(@PathVariable("scheduleId") Integer scheduleId, @RequestBody @MapTo(Schedule.class) Map<String, Object> schedulePatch) {
        LOGGER.debug("Partially updating Schedule with id: {}" , scheduleId);

        Schedule schedule = scheduleService.partialUpdate(scheduleId, schedulePatch);
        LOGGER.debug("Schedule details after partial update: {}" , schedule);

        return schedule;
    }

    @ApiOperation(value = "Deletes the Schedule instance associated with the given id.")
    @DeleteMapping(value = "/{scheduleId:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteSchedule(@PathVariable("scheduleId") Integer scheduleId) {
        LOGGER.debug("Deleting Schedule with id: {}" , scheduleId);

        Schedule deletedSchedule = scheduleService.delete(scheduleId);

        return deletedSchedule != null;
    }

    /**
     * @deprecated Use {@link #findSchedules(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of Schedule instances matching the search criteria.")
    @PostMapping(value = "/search")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Schedule> searchSchedulesByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering Schedules list by query filter:{}", (Object) queryFilters);
        return scheduleService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Schedule instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @GetMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Schedule> findSchedules(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Schedules list by filter:", query);
        return scheduleService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Schedule instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @PostMapping(value="/filter", consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Schedule> filterSchedules(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Schedules list by filter", query);
        return scheduleService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param.")
    @GetMapping(value = "/export/{exportType}", produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportSchedules(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return scheduleService.export(exportType, query, pageable);
    }

    @ApiOperation(value = "Returns a URL to download a file for the data matching the optional query (q) request param and the required fields provided in the Export Options.") 
    @PostMapping(value = "/export", consumes = "application/json")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportSchedulesAndGetURL(@RequestBody DataExportOptions exportOptions, Pageable pageable) {
        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = Schedule.class.getSimpleName();
        }
        exportedFileName += exportOptions.getExportType().getExtension();
        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName, outputStream -> scheduleService.export(exportOptions, pageable, outputStream));
        return new StringWrapper(exportedUrl);
    }

	@ApiOperation(value = "Returns the total count of Schedule instances matching the optional query (q) request param.")
	@GetMapping(value = "/count")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countSchedules( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting Schedules");
		return scheduleService.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@PostMapping(value = "/aggregations")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getScheduleAggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return scheduleService.getAggregatedValues(aggregationInfo, pageable);
    }

    @GetMapping(value="/{scheduleId:.+}/scheduledEmployees")
    @ApiOperation(value = "Gets the scheduledEmployees instance associated with the given id.")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<ScheduledEmployee> findAssociatedScheduledEmployees(@PathVariable("scheduleId") Integer scheduleId, Pageable pageable) {

        LOGGER.debug("Fetching all associated scheduledEmployees");
        return scheduleService.findAssociatedScheduledEmployees(scheduleId, pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service ScheduleService instance
	 */
	protected void setScheduleService(ScheduleService service) {
		this.scheduleService = service;
	}

}
