/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.commons.file.manager.ExportedFileManager;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.tools.api.core.annotations.MapTo;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.wavemaker.when_to_work.when2work.Category;
import com.wavemaker.when_to_work.when2work.EmployeeSkill;
import com.wavemaker.when_to_work.when2work.GroupSkill;
import com.wavemaker.when_to_work.when2work.ScheduledEmployee;
import com.wavemaker.when_to_work.when2work.Skill;
import com.wavemaker.when_to_work.when2work.service.SkillService;


/**
 * Controller object for domain model class Skill.
 * @see Skill
 */
@RestController("when2work.SkillController")
@Api(value = "SkillController", description = "Exposes APIs to work with Skill resource.")
@RequestMapping("/when2work/Skill")
public class SkillController {

    private static final Logger LOGGER = LoggerFactory.getLogger(SkillController.class);

    @Autowired
	@Qualifier("when2work.SkillService")
	private SkillService skillService;

	@Autowired
	private ExportedFileManager exportedFileManager;

	@ApiOperation(value = "Creates a new Skill instance.")
    @PostMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Skill createSkill(@RequestBody Skill skill) {
		LOGGER.debug("Create Skill with information: {}" , skill);

		skill = skillService.create(skill);
		LOGGER.debug("Created Skill with information: {}" , skill);

	    return skill;
	}

    @ApiOperation(value = "Returns the Skill instance associated with the given id.")
    @GetMapping(value = "/{skillId:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Skill getSkill(@PathVariable("skillId") Integer skillId) {
        LOGGER.debug("Getting Skill with id: {}" , skillId);

        Skill foundSkill = skillService.getById(skillId);
        LOGGER.debug("Skill details with id: {}" , foundSkill);

        return foundSkill;
    }

    @ApiOperation(value = "Updates the Skill instance associated with the given id.")
    @PutMapping(value = "/{skillId:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Skill editSkill(@PathVariable("skillId") Integer skillId, @RequestBody Skill skill) {
        LOGGER.debug("Editing Skill with id: {}" , skill.getSkillId());

        skill.setSkillId(skillId);
        skill = skillService.update(skill);
        LOGGER.debug("Skill details with id: {}" , skill);

        return skill;
    }
    
    @ApiOperation(value = "Partially updates the Skill instance associated with the given id.")
    @PatchMapping(value = "/{skillId:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Skill patchSkill(@PathVariable("skillId") Integer skillId, @RequestBody @MapTo(Skill.class) Map<String, Object> skillPatch) {
        LOGGER.debug("Partially updating Skill with id: {}" , skillId);

        Skill skill = skillService.partialUpdate(skillId, skillPatch);
        LOGGER.debug("Skill details after partial update: {}" , skill);

        return skill;
    }

    @ApiOperation(value = "Deletes the Skill instance associated with the given id.")
    @DeleteMapping(value = "/{skillId:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteSkill(@PathVariable("skillId") Integer skillId) {
        LOGGER.debug("Deleting Skill with id: {}" , skillId);

        Skill deletedSkill = skillService.delete(skillId);

        return deletedSkill != null;
    }

    /**
     * @deprecated Use {@link #findSkills(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of Skill instances matching the search criteria.")
    @PostMapping(value = "/search")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Skill> searchSkillsByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering Skills list by query filter:{}", (Object) queryFilters);
        return skillService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Skill instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @GetMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Skill> findSkills(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Skills list by filter:", query);
        return skillService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Skill instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @PostMapping(value="/filter", consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Skill> filterSkills(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Skills list by filter", query);
        return skillService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param.")
    @GetMapping(value = "/export/{exportType}", produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportSkills(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return skillService.export(exportType, query, pageable);
    }

    @ApiOperation(value = "Returns a URL to download a file for the data matching the optional query (q) request param and the required fields provided in the Export Options.") 
    @PostMapping(value = "/export", consumes = "application/json")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportSkillsAndGetURL(@RequestBody DataExportOptions exportOptions, Pageable pageable) {
        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = Skill.class.getSimpleName();
        }
        exportedFileName += exportOptions.getExportType().getExtension();
        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName, outputStream -> skillService.export(exportOptions, pageable, outputStream));
        return new StringWrapper(exportedUrl);
    }

	@ApiOperation(value = "Returns the total count of Skill instances matching the optional query (q) request param.")
	@GetMapping(value = "/count")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countSkills( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting Skills");
		return skillService.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@PostMapping(value = "/aggregations")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getSkillAggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return skillService.getAggregatedValues(aggregationInfo, pageable);
    }

    @GetMapping(value="/{skillId:.+}/categories")
    @ApiOperation(value = "Gets the categories instance associated with the given id.")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Category> findAssociatedCategories(@PathVariable("skillId") Integer skillId, Pageable pageable) {

        LOGGER.debug("Fetching all associated categories");
        return skillService.findAssociatedCategories(skillId, pageable);
    }

    @GetMapping(value="/{skillId:.+}/employeeSkills")
    @ApiOperation(value = "Gets the employeeSkills instance associated with the given id.")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<EmployeeSkill> findAssociatedEmployeeSkills(@PathVariable("skillId") Integer skillId, Pageable pageable) {

        LOGGER.debug("Fetching all associated employeeSkills");
        return skillService.findAssociatedEmployeeSkills(skillId, pageable);
    }

    @GetMapping(value="/{skillId:.+}/groupSkills")
    @ApiOperation(value = "Gets the groupSkills instance associated with the given id.")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<GroupSkill> findAssociatedGroupSkills(@PathVariable("skillId") Integer skillId, Pageable pageable) {

        LOGGER.debug("Fetching all associated groupSkills");
        return skillService.findAssociatedGroupSkills(skillId, pageable);
    }

    @GetMapping(value="/{skillId:.+}/scheduledEmployees")
    @ApiOperation(value = "Gets the scheduledEmployees instance associated with the given id.")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<ScheduledEmployee> findAssociatedScheduledEmployees(@PathVariable("skillId") Integer skillId, Pageable pageable) {

        LOGGER.debug("Fetching all associated scheduledEmployees");
        return skillService.findAssociatedScheduledEmployees(skillId, pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service SkillService instance
	 */
	protected void setSkillService(SkillService service) {
		this.skillService = service;
	}

}
