/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.commons.file.manager.ExportedFileManager;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.tools.api.core.annotations.MapTo;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.wavemaker.when_to_work.when2work.GroupSkill;
import com.wavemaker.when_to_work.when2work.SkillGroup;
import com.wavemaker.when_to_work.when2work.service.SkillGroupService;


/**
 * Controller object for domain model class SkillGroup.
 * @see SkillGroup
 */
@RestController("when2work.SkillGroupController")
@Api(value = "SkillGroupController", description = "Exposes APIs to work with SkillGroup resource.")
@RequestMapping("/when2work/SkillGroup")
public class SkillGroupController {

    private static final Logger LOGGER = LoggerFactory.getLogger(SkillGroupController.class);

    @Autowired
	@Qualifier("when2work.SkillGroupService")
	private SkillGroupService skillGroupService;

	@Autowired
	private ExportedFileManager exportedFileManager;

	@ApiOperation(value = "Creates a new SkillGroup instance.")
    @PostMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public SkillGroup createSkillGroup(@RequestBody SkillGroup skillGroup) {
		LOGGER.debug("Create SkillGroup with information: {}" , skillGroup);

		skillGroup = skillGroupService.create(skillGroup);
		LOGGER.debug("Created SkillGroup with information: {}" , skillGroup);

	    return skillGroup;
	}

    @ApiOperation(value = "Returns the SkillGroup instance associated with the given id.")
    @GetMapping(value = "/{groupId:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public SkillGroup getSkillGroup(@PathVariable("groupId") Integer groupId) {
        LOGGER.debug("Getting SkillGroup with id: {}" , groupId);

        SkillGroup foundSkillGroup = skillGroupService.getById(groupId);
        LOGGER.debug("SkillGroup details with id: {}" , foundSkillGroup);

        return foundSkillGroup;
    }

    @ApiOperation(value = "Updates the SkillGroup instance associated with the given id.")
    @PutMapping(value = "/{groupId:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public SkillGroup editSkillGroup(@PathVariable("groupId") Integer groupId, @RequestBody SkillGroup skillGroup) {
        LOGGER.debug("Editing SkillGroup with id: {}" , skillGroup.getGroupId());

        skillGroup.setGroupId(groupId);
        skillGroup = skillGroupService.update(skillGroup);
        LOGGER.debug("SkillGroup details with id: {}" , skillGroup);

        return skillGroup;
    }
    
    @ApiOperation(value = "Partially updates the SkillGroup instance associated with the given id.")
    @PatchMapping(value = "/{groupId:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public SkillGroup patchSkillGroup(@PathVariable("groupId") Integer groupId, @RequestBody @MapTo(SkillGroup.class) Map<String, Object> skillGroupPatch) {
        LOGGER.debug("Partially updating SkillGroup with id: {}" , groupId);

        SkillGroup skillGroup = skillGroupService.partialUpdate(groupId, skillGroupPatch);
        LOGGER.debug("SkillGroup details after partial update: {}" , skillGroup);

        return skillGroup;
    }

    @ApiOperation(value = "Deletes the SkillGroup instance associated with the given id.")
    @DeleteMapping(value = "/{groupId:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteSkillGroup(@PathVariable("groupId") Integer groupId) {
        LOGGER.debug("Deleting SkillGroup with id: {}" , groupId);

        SkillGroup deletedSkillGroup = skillGroupService.delete(groupId);

        return deletedSkillGroup != null;
    }

    /**
     * @deprecated Use {@link #findSkillGroups(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of SkillGroup instances matching the search criteria.")
    @PostMapping(value = "/search")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<SkillGroup> searchSkillGroupsByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering SkillGroups list by query filter:{}", (Object) queryFilters);
        return skillGroupService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of SkillGroup instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @GetMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<SkillGroup> findSkillGroups(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering SkillGroups list by filter:", query);
        return skillGroupService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of SkillGroup instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @PostMapping(value="/filter", consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<SkillGroup> filterSkillGroups(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering SkillGroups list by filter", query);
        return skillGroupService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param.")
    @GetMapping(value = "/export/{exportType}", produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportSkillGroups(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return skillGroupService.export(exportType, query, pageable);
    }

    @ApiOperation(value = "Returns a URL to download a file for the data matching the optional query (q) request param and the required fields provided in the Export Options.") 
    @PostMapping(value = "/export", consumes = "application/json")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportSkillGroupsAndGetURL(@RequestBody DataExportOptions exportOptions, Pageable pageable) {
        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = SkillGroup.class.getSimpleName();
        }
        exportedFileName += exportOptions.getExportType().getExtension();
        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName, outputStream -> skillGroupService.export(exportOptions, pageable, outputStream));
        return new StringWrapper(exportedUrl);
    }

	@ApiOperation(value = "Returns the total count of SkillGroup instances matching the optional query (q) request param.")
	@GetMapping(value = "/count")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countSkillGroups( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting SkillGroups");
		return skillGroupService.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@PostMapping(value = "/aggregations")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getSkillGroupAggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return skillGroupService.getAggregatedValues(aggregationInfo, pageable);
    }

    @GetMapping(value="/{groupId:.+}/groupSkills")
    @ApiOperation(value = "Gets the groupSkills instance associated with the given id.")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<GroupSkill> findAssociatedGroupSkills(@PathVariable("groupId") Integer groupId, Pageable pageable) {

        LOGGER.debug("Fetching all associated groupSkills");
        return skillGroupService.findAssociatedGroupSkills(groupId, pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service SkillGroupService instance
	 */
	protected void setSkillGroupService(SkillGroupService service) {
		this.skillGroupService = service;
	}

}
