/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.when_to_work.categoryList.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.when_to_work.categoryList.model.ResponseCategoriesEntryItem;
import com.wavemaker.when_to_work.categoryList.model.ResponseGroupsEntryItem;
import java.util.ArrayList;
import java.util.List;
/**
 * RootResponse
 */

public class RootResponse {
  @JsonProperty("groups")
  private List<ResponseGroupsEntryItem> groups = new ArrayList<>();

  @JsonProperty("categories")
  private List<ResponseCategoriesEntryItem> categories = new ArrayList<>();

  public RootResponse groups(List<ResponseGroupsEntryItem> groups) {
    this.groups = groups;
    return this;
  }

  public RootResponse addGroupsItem(ResponseGroupsEntryItem groupsItem) {
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * Get groups
   * @return groups
  **/
  public List<ResponseGroupsEntryItem> getGroups() {
    return groups;
  }

  public void setGroups(List<ResponseGroupsEntryItem> groups) {
    this.groups = groups;
  }

  public RootResponse categories(List<ResponseCategoriesEntryItem> categories) {
    this.categories = categories;
    return this;
  }

  public RootResponse addCategoriesItem(ResponseCategoriesEntryItem categoriesItem) {
    this.categories.add(categoriesItem);
    return this;
  }

   /**
   * Get categories
   * @return categories
  **/
  public List<ResponseCategoriesEntryItem> getCategories() {
    return categories;
  }

  public void setCategories(List<ResponseCategoriesEntryItem> categories) {
    this.categories = categories;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootResponse RootResponse = (RootResponse) o;
    return Objects.equals(this.groups, RootResponse.groups) &&
        Objects.equals(this.categories, RootResponse.categories);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groups, categories);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootResponse {\n");
    
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
