/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.when_to_work.deletePosition.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.when_to_work.deletePosition.model.ResponseDiv;
import java.util.ArrayList;
import java.util.List;
/**
 * ResponseParsererror
 */

public class ResponseParsererror {
  @JsonProperty("div")
  private ResponseDiv div = null;

  @JsonProperty("style")
  private String style = null;

  @JsonProperty("h3")
  private List<String> h3 = new ArrayList<>();

  public ResponseParsererror div(ResponseDiv div) {
    this.div = div;
    return this;
  }

   /**
   * Get div
   * @return div
  **/
  public ResponseDiv getDiv() {
    return div;
  }

  public void setDiv(ResponseDiv div) {
    this.div = div;
  }

  public ResponseParsererror style(String style) {
    this.style = style;
    return this;
  }

   /**
   * Get style
   * @return style
  **/
  public String getStyle() {
    return style;
  }

  public void setStyle(String style) {
    this.style = style;
  }

  public ResponseParsererror h3(List<String> h3) {
    this.h3 = h3;
    return this;
  }

  public ResponseParsererror addH3Item(String h3Item) {
    this.h3.add(h3Item);
    return this;
  }

   /**
   * Get h3
   * @return h3
  **/
  public List<String> getH3() {
    return h3;
  }

  public void setH3(List<String> h3) {
    this.h3 = h3;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseParsererror Response_parsererror = (ResponseParsererror) o;
    return Objects.equals(this.div, Response_parsererror.div) &&
        Objects.equals(this.style, Response_parsererror.style) &&
        Objects.equals(this.h3, Response_parsererror.h3);
  }

  @Override
  public int hashCode() {
    return Objects.hash(div, style, h3);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseParsererror {\n");
    
    sb.append("    div: ").append(toIndentedString(div)).append("\n");
    sb.append("    style: ").append(toIndentedString(style)).append("\n");
    sb.append("    h3: ").append(toIndentedString(h3)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
