/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.when_to_work.getAdditionalManagers.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponsePermissions
 */

public class ResponsePermissions {
  @JsonProperty("canPublishSchedules")
  private Boolean canPublishSchedules = null;

  @JsonProperty("canApproveTrades")
  private Boolean canApproveTrades = null;

  @JsonProperty("canEditEmployees")
  private Boolean canEditEmployees = null;

  @JsonProperty("canUnpublishSchedules")
  private Boolean canUnpublishSchedules = null;

  @JsonProperty("canEditShifts")
  private Boolean canEditShifts = null;

  @JsonProperty("canAddEmployees")
  private Boolean canAddEmployees = null;

  @JsonProperty("canAutofillShifts")
  private Boolean canAutofillShifts = null;

  @JsonProperty("canChangeCompanySettings")
  private Boolean canChangeCompanySettings = null;

  @JsonProperty("canManageTeamMembers")
  private Boolean canManageTeamMembers = null;

  @JsonProperty("canUploadShifts")
  private Boolean canUploadShifts = null;

  @JsonProperty("canSaveTemplates")
  private Boolean canSaveTemplates = null;

  @JsonProperty("canApproveTimeOff")
  private Boolean canApproveTimeOff = null;

  @JsonProperty("isMainManager")
  private Boolean isMainManager = null;

  @JsonProperty("canAddShifts")
  private Boolean canAddShifts = null;

  @JsonProperty("canImportTemplates")
  private Boolean canImportTemplates = null;

  @JsonProperty("canViewPayRates")
  private Boolean canViewPayRates = null;

  @JsonProperty("canManageCategories")
  private Boolean canManageCategories = null;

  @JsonProperty("canReceiveManagerNotifications")
  private Boolean canReceiveManagerNotifications = null;

  @JsonProperty("canManagePositions")
  private Boolean canManagePositions = null;

  @JsonProperty("canClearSchedules")
  private Boolean canClearSchedules = null;

  public ResponsePermissions canPublishSchedules(Boolean canPublishSchedules) {
    this.canPublishSchedules = canPublishSchedules;
    return this;
  }

   /**
   * Get canPublishSchedules
   * @return canPublishSchedules
  **/
  public Boolean isCanPublishSchedules() {
    return canPublishSchedules;
  }

  public void setCanPublishSchedules(Boolean canPublishSchedules) {
    this.canPublishSchedules = canPublishSchedules;
  }

  public ResponsePermissions canApproveTrades(Boolean canApproveTrades) {
    this.canApproveTrades = canApproveTrades;
    return this;
  }

   /**
   * Get canApproveTrades
   * @return canApproveTrades
  **/
  public Boolean isCanApproveTrades() {
    return canApproveTrades;
  }

  public void setCanApproveTrades(Boolean canApproveTrades) {
    this.canApproveTrades = canApproveTrades;
  }

  public ResponsePermissions canEditEmployees(Boolean canEditEmployees) {
    this.canEditEmployees = canEditEmployees;
    return this;
  }

   /**
   * Get canEditEmployees
   * @return canEditEmployees
  **/
  public Boolean isCanEditEmployees() {
    return canEditEmployees;
  }

  public void setCanEditEmployees(Boolean canEditEmployees) {
    this.canEditEmployees = canEditEmployees;
  }

  public ResponsePermissions canUnpublishSchedules(Boolean canUnpublishSchedules) {
    this.canUnpublishSchedules = canUnpublishSchedules;
    return this;
  }

   /**
   * Get canUnpublishSchedules
   * @return canUnpublishSchedules
  **/
  public Boolean isCanUnpublishSchedules() {
    return canUnpublishSchedules;
  }

  public void setCanUnpublishSchedules(Boolean canUnpublishSchedules) {
    this.canUnpublishSchedules = canUnpublishSchedules;
  }

  public ResponsePermissions canEditShifts(Boolean canEditShifts) {
    this.canEditShifts = canEditShifts;
    return this;
  }

   /**
   * Get canEditShifts
   * @return canEditShifts
  **/
  public Boolean isCanEditShifts() {
    return canEditShifts;
  }

  public void setCanEditShifts(Boolean canEditShifts) {
    this.canEditShifts = canEditShifts;
  }

  public ResponsePermissions canAddEmployees(Boolean canAddEmployees) {
    this.canAddEmployees = canAddEmployees;
    return this;
  }

   /**
   * Get canAddEmployees
   * @return canAddEmployees
  **/
  public Boolean isCanAddEmployees() {
    return canAddEmployees;
  }

  public void setCanAddEmployees(Boolean canAddEmployees) {
    this.canAddEmployees = canAddEmployees;
  }

  public ResponsePermissions canAutofillShifts(Boolean canAutofillShifts) {
    this.canAutofillShifts = canAutofillShifts;
    return this;
  }

   /**
   * Get canAutofillShifts
   * @return canAutofillShifts
  **/
  public Boolean isCanAutofillShifts() {
    return canAutofillShifts;
  }

  public void setCanAutofillShifts(Boolean canAutofillShifts) {
    this.canAutofillShifts = canAutofillShifts;
  }

  public ResponsePermissions canChangeCompanySettings(Boolean canChangeCompanySettings) {
    this.canChangeCompanySettings = canChangeCompanySettings;
    return this;
  }

   /**
   * Get canChangeCompanySettings
   * @return canChangeCompanySettings
  **/
  public Boolean isCanChangeCompanySettings() {
    return canChangeCompanySettings;
  }

  public void setCanChangeCompanySettings(Boolean canChangeCompanySettings) {
    this.canChangeCompanySettings = canChangeCompanySettings;
  }

  public ResponsePermissions canManageTeamMembers(Boolean canManageTeamMembers) {
    this.canManageTeamMembers = canManageTeamMembers;
    return this;
  }

   /**
   * Get canManageTeamMembers
   * @return canManageTeamMembers
  **/
  public Boolean isCanManageTeamMembers() {
    return canManageTeamMembers;
  }

  public void setCanManageTeamMembers(Boolean canManageTeamMembers) {
    this.canManageTeamMembers = canManageTeamMembers;
  }

  public ResponsePermissions canUploadShifts(Boolean canUploadShifts) {
    this.canUploadShifts = canUploadShifts;
    return this;
  }

   /**
   * Get canUploadShifts
   * @return canUploadShifts
  **/
  public Boolean isCanUploadShifts() {
    return canUploadShifts;
  }

  public void setCanUploadShifts(Boolean canUploadShifts) {
    this.canUploadShifts = canUploadShifts;
  }

  public ResponsePermissions canSaveTemplates(Boolean canSaveTemplates) {
    this.canSaveTemplates = canSaveTemplates;
    return this;
  }

   /**
   * Get canSaveTemplates
   * @return canSaveTemplates
  **/
  public Boolean isCanSaveTemplates() {
    return canSaveTemplates;
  }

  public void setCanSaveTemplates(Boolean canSaveTemplates) {
    this.canSaveTemplates = canSaveTemplates;
  }

  public ResponsePermissions canApproveTimeOff(Boolean canApproveTimeOff) {
    this.canApproveTimeOff = canApproveTimeOff;
    return this;
  }

   /**
   * Get canApproveTimeOff
   * @return canApproveTimeOff
  **/
  public Boolean isCanApproveTimeOff() {
    return canApproveTimeOff;
  }

  public void setCanApproveTimeOff(Boolean canApproveTimeOff) {
    this.canApproveTimeOff = canApproveTimeOff;
  }

  public ResponsePermissions isMainManager(Boolean isMainManager) {
    this.isMainManager = isMainManager;
    return this;
  }

   /**
   * Get isMainManager
   * @return isMainManager
  **/
  public Boolean isIsMainManager() {
    return isMainManager;
  }

  public void setIsMainManager(Boolean isMainManager) {
    this.isMainManager = isMainManager;
  }

  public ResponsePermissions canAddShifts(Boolean canAddShifts) {
    this.canAddShifts = canAddShifts;
    return this;
  }

   /**
   * Get canAddShifts
   * @return canAddShifts
  **/
  public Boolean isCanAddShifts() {
    return canAddShifts;
  }

  public void setCanAddShifts(Boolean canAddShifts) {
    this.canAddShifts = canAddShifts;
  }

  public ResponsePermissions canImportTemplates(Boolean canImportTemplates) {
    this.canImportTemplates = canImportTemplates;
    return this;
  }

   /**
   * Get canImportTemplates
   * @return canImportTemplates
  **/
  public Boolean isCanImportTemplates() {
    return canImportTemplates;
  }

  public void setCanImportTemplates(Boolean canImportTemplates) {
    this.canImportTemplates = canImportTemplates;
  }

  public ResponsePermissions canViewPayRates(Boolean canViewPayRates) {
    this.canViewPayRates = canViewPayRates;
    return this;
  }

   /**
   * Get canViewPayRates
   * @return canViewPayRates
  **/
  public Boolean isCanViewPayRates() {
    return canViewPayRates;
  }

  public void setCanViewPayRates(Boolean canViewPayRates) {
    this.canViewPayRates = canViewPayRates;
  }

  public ResponsePermissions canManageCategories(Boolean canManageCategories) {
    this.canManageCategories = canManageCategories;
    return this;
  }

   /**
   * Get canManageCategories
   * @return canManageCategories
  **/
  public Boolean isCanManageCategories() {
    return canManageCategories;
  }

  public void setCanManageCategories(Boolean canManageCategories) {
    this.canManageCategories = canManageCategories;
  }

  public ResponsePermissions canReceiveManagerNotifications(Boolean canReceiveManagerNotifications) {
    this.canReceiveManagerNotifications = canReceiveManagerNotifications;
    return this;
  }

   /**
   * Get canReceiveManagerNotifications
   * @return canReceiveManagerNotifications
  **/
  public Boolean isCanReceiveManagerNotifications() {
    return canReceiveManagerNotifications;
  }

  public void setCanReceiveManagerNotifications(Boolean canReceiveManagerNotifications) {
    this.canReceiveManagerNotifications = canReceiveManagerNotifications;
  }

  public ResponsePermissions canManagePositions(Boolean canManagePositions) {
    this.canManagePositions = canManagePositions;
    return this;
  }

   /**
   * Get canManagePositions
   * @return canManagePositions
  **/
  public Boolean isCanManagePositions() {
    return canManagePositions;
  }

  public void setCanManagePositions(Boolean canManagePositions) {
    this.canManagePositions = canManagePositions;
  }

  public ResponsePermissions canClearSchedules(Boolean canClearSchedules) {
    this.canClearSchedules = canClearSchedules;
    return this;
  }

   /**
   * Get canClearSchedules
   * @return canClearSchedules
  **/
  public Boolean isCanClearSchedules() {
    return canClearSchedules;
  }

  public void setCanClearSchedules(Boolean canClearSchedules) {
    this.canClearSchedules = canClearSchedules;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponsePermissions Response_permissions = (ResponsePermissions) o;
    return Objects.equals(this.canPublishSchedules, Response_permissions.canPublishSchedules) &&
        Objects.equals(this.canApproveTrades, Response_permissions.canApproveTrades) &&
        Objects.equals(this.canEditEmployees, Response_permissions.canEditEmployees) &&
        Objects.equals(this.canUnpublishSchedules, Response_permissions.canUnpublishSchedules) &&
        Objects.equals(this.canEditShifts, Response_permissions.canEditShifts) &&
        Objects.equals(this.canAddEmployees, Response_permissions.canAddEmployees) &&
        Objects.equals(this.canAutofillShifts, Response_permissions.canAutofillShifts) &&
        Objects.equals(this.canChangeCompanySettings, Response_permissions.canChangeCompanySettings) &&
        Objects.equals(this.canManageTeamMembers, Response_permissions.canManageTeamMembers) &&
        Objects.equals(this.canUploadShifts, Response_permissions.canUploadShifts) &&
        Objects.equals(this.canSaveTemplates, Response_permissions.canSaveTemplates) &&
        Objects.equals(this.canApproveTimeOff, Response_permissions.canApproveTimeOff) &&
        Objects.equals(this.isMainManager, Response_permissions.isMainManager) &&
        Objects.equals(this.canAddShifts, Response_permissions.canAddShifts) &&
        Objects.equals(this.canImportTemplates, Response_permissions.canImportTemplates) &&
        Objects.equals(this.canViewPayRates, Response_permissions.canViewPayRates) &&
        Objects.equals(this.canManageCategories, Response_permissions.canManageCategories) &&
        Objects.equals(this.canReceiveManagerNotifications, Response_permissions.canReceiveManagerNotifications) &&
        Objects.equals(this.canManagePositions, Response_permissions.canManagePositions) &&
        Objects.equals(this.canClearSchedules, Response_permissions.canClearSchedules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canPublishSchedules, canApproveTrades, canEditEmployees, canUnpublishSchedules, canEditShifts, canAddEmployees, canAutofillShifts, canChangeCompanySettings, canManageTeamMembers, canUploadShifts, canSaveTemplates, canApproveTimeOff, isMainManager, canAddShifts, canImportTemplates, canViewPayRates, canManageCategories, canReceiveManagerNotifications, canManagePositions, canClearSchedules);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponsePermissions {\n");
    
    sb.append("    canPublishSchedules: ").append(toIndentedString(canPublishSchedules)).append("\n");
    sb.append("    canApproveTrades: ").append(toIndentedString(canApproveTrades)).append("\n");
    sb.append("    canEditEmployees: ").append(toIndentedString(canEditEmployees)).append("\n");
    sb.append("    canUnpublishSchedules: ").append(toIndentedString(canUnpublishSchedules)).append("\n");
    sb.append("    canEditShifts: ").append(toIndentedString(canEditShifts)).append("\n");
    sb.append("    canAddEmployees: ").append(toIndentedString(canAddEmployees)).append("\n");
    sb.append("    canAutofillShifts: ").append(toIndentedString(canAutofillShifts)).append("\n");
    sb.append("    canChangeCompanySettings: ").append(toIndentedString(canChangeCompanySettings)).append("\n");
    sb.append("    canManageTeamMembers: ").append(toIndentedString(canManageTeamMembers)).append("\n");
    sb.append("    canUploadShifts: ").append(toIndentedString(canUploadShifts)).append("\n");
    sb.append("    canSaveTemplates: ").append(toIndentedString(canSaveTemplates)).append("\n");
    sb.append("    canApproveTimeOff: ").append(toIndentedString(canApproveTimeOff)).append("\n");
    sb.append("    isMainManager: ").append(toIndentedString(isMainManager)).append("\n");
    sb.append("    canAddShifts: ").append(toIndentedString(canAddShifts)).append("\n");
    sb.append("    canImportTemplates: ").append(toIndentedString(canImportTemplates)).append("\n");
    sb.append("    canViewPayRates: ").append(toIndentedString(canViewPayRates)).append("\n");
    sb.append("    canManageCategories: ").append(toIndentedString(canManageCategories)).append("\n");
    sb.append("    canReceiveManagerNotifications: ").append(toIndentedString(canReceiveManagerNotifications)).append("\n");
    sb.append("    canManagePositions: ").append(toIndentedString(canManagePositions)).append("\n");
    sb.append("    canClearSchedules: ").append(toIndentedString(canClearSchedules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
