sonar.projectKey=when_to_work
sonar.projectName=when_to_work
sonar.sourceEncoding=UTF-8

#################################
# SOURCE CODE
#################################

sonar.sources=src/main/java,src/main/webapp/pages

#################################
# FILE SUFFIXES TO SCAN
#################################

# Java
sonar.java.file.suffixes=.java

# JavaScript
sonar.javascript.file.suffixes=.js

# CSS
sonar.css.file.suffixes=.css

# HTML
sonar.web.file.suffixes=.html

# XML
sonar.xml.file.suffixes=.xml

# JSON (only variables.json)
sonar.json.file.suffixes=.variables.json

#################################
# Disable Java binaries (UI project)
#################################

#sonar.java.binaries=
# scan java binaries
# compiled classes (required for proper Java analysis)
sonar.java.binaries=target/classes


#################################
# DUPLICATION SETTINGS
#################################

sonar.cpd.exclusions=**/pages/**/*.html
sonar.cpd.javascript.minimumTokens=150

#################################
# TEST FILES
#################################

sonar.tests=src/main/webapp/pages
sonar.test.inclusions=**/*.test.js

#################################
# JEST COVERAGE
#################################

sonar.javascript.lcov.reportPaths=coverage/lcov.info

#################################
# EXCLUSIONS
#################################

sonar.exclusions=**/*.min.json,generated-angular-app/**/*,**/src/main/webapp/resources/files/**
