/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.when_to_work.svDeleteShiftById.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseDiv
 */

public class ResponseDiv {
  @JsonProperty("__text")
  private String __text = null;

  @JsonProperty("style")
  private String style = null;

  public ResponseDiv __text(String __text) {
    this.__text = __text;
    return this;
  }

   /**
   * Get __text
   * @return __text
  **/
  public String getText() {
    return __text;
  }

  public void setText(String __text) {
    this.__text = __text;
  }

  public ResponseDiv style(String style) {
    this.style = style;
    return this;
  }

   /**
   * Get style
   * @return style
  **/
  public String getStyle() {
    return style;
  }

  public void setStyle(String style) {
    this.style = style;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseDiv Response_div = (ResponseDiv) o;
    return Objects.equals(this.__text, Response_div.__text) &&
        Objects.equals(this.style, Response_div.style);
  }

  @Override
  public int hashCode() {
    return Objects.hash(__text, style);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseDiv {\n");
    
    sb.append("    __text: ").append(toIndentedString(__text)).append("\n");
    sb.append("    style: ").append(toIndentedString(style)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
