/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.when_to_work.getPositionGroup.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.when_to_work.getPositionGroup.model.ResponsePositionsEntryItem;
import java.util.ArrayList;
import java.util.List;
/**
 * ResponsePositionGroupsEntryItem
 */

public class ResponsePositionGroupsEntryItem {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("positions")
  private List<ResponsePositionsEntryItem> positions = new ArrayList<>();

  @JsonProperty("id")
  private Integer id = null;

  public ResponsePositionGroupsEntryItem name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ResponsePositionGroupsEntryItem positions(List<ResponsePositionsEntryItem> positions) {
    this.positions = positions;
    return this;
  }

  public ResponsePositionGroupsEntryItem addPositionsItem(ResponsePositionsEntryItem positionsItem) {
    this.positions.add(positionsItem);
    return this;
  }

   /**
   * Get positions
   * @return positions
  **/
  public List<ResponsePositionsEntryItem> getPositions() {
    return positions;
  }

  public void setPositions(List<ResponsePositionsEntryItem> positions) {
    this.positions = positions;
  }

  public ResponsePositionGroupsEntryItem id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponsePositionGroupsEntryItem Response_positionGroupsEntryItem = (ResponsePositionGroupsEntryItem) o;
    return Objects.equals(this.name, Response_positionGroupsEntryItem.name) &&
        Objects.equals(this.positions, Response_positionGroupsEntryItem.positions) &&
        Objects.equals(this.id, Response_positionGroupsEntryItem.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, positions, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponsePositionGroupsEntryItem {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    positions: ").append(toIndentedString(positions)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
