/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.when_to_work.getPositionViewScheduling.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.when_to_work.getPositionViewScheduling.model.ResponsePositionsEntryItem;
import java.util.ArrayList;
import java.util.List;
/**
 * ResponseDatesEntryItem
 */

public class ResponseDatesEntryItem {
  @JsonProperty("date")
  private String date = null;

  @JsonProperty("totalDuration")
  private Integer totalDuration = null;

  @JsonProperty("shiftCount")
  private Integer shiftCount = null;

  @JsonProperty("weekday")
  private String weekday = null;

  @JsonProperty("positions")
  private List<ResponsePositionsEntryItem> positions = new ArrayList<>();

  public ResponseDatesEntryItem date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public ResponseDatesEntryItem totalDuration(Integer totalDuration) {
    this.totalDuration = totalDuration;
    return this;
  }

   /**
   * Get totalDuration
   * @return totalDuration
  **/
  public Integer getTotalDuration() {
    return totalDuration;
  }

  public void setTotalDuration(Integer totalDuration) {
    this.totalDuration = totalDuration;
  }

  public ResponseDatesEntryItem shiftCount(Integer shiftCount) {
    this.shiftCount = shiftCount;
    return this;
  }

   /**
   * Get shiftCount
   * @return shiftCount
  **/
  public Integer getShiftCount() {
    return shiftCount;
  }

  public void setShiftCount(Integer shiftCount) {
    this.shiftCount = shiftCount;
  }

  public ResponseDatesEntryItem weekday(String weekday) {
    this.weekday = weekday;
    return this;
  }

   /**
   * Get weekday
   * @return weekday
  **/
  public String getWeekday() {
    return weekday;
  }

  public void setWeekday(String weekday) {
    this.weekday = weekday;
  }

  public ResponseDatesEntryItem positions(List<ResponsePositionsEntryItem> positions) {
    this.positions = positions;
    return this;
  }

  public ResponseDatesEntryItem addPositionsItem(ResponsePositionsEntryItem positionsItem) {
    this.positions.add(positionsItem);
    return this;
  }

   /**
   * Get positions
   * @return positions
  **/
  public List<ResponsePositionsEntryItem> getPositions() {
    return positions;
  }

  public void setPositions(List<ResponsePositionsEntryItem> positions) {
    this.positions = positions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseDatesEntryItem Response_datesEntryItem = (ResponseDatesEntryItem) o;
    return Objects.equals(this.date, Response_datesEntryItem.date) &&
        Objects.equals(this.totalDuration, Response_datesEntryItem.totalDuration) &&
        Objects.equals(this.shiftCount, Response_datesEntryItem.shiftCount) &&
        Objects.equals(this.weekday, Response_datesEntryItem.weekday) &&
        Objects.equals(this.positions, Response_datesEntryItem.positions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, totalDuration, shiftCount, weekday, positions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseDatesEntryItem {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    totalDuration: ").append(toIndentedString(totalDuration)).append("\n");
    sb.append("    shiftCount: ").append(toIndentedString(shiftCount)).append("\n");
    sb.append("    weekday: ").append(toIndentedString(weekday)).append("\n");
    sb.append("    positions: ").append(toIndentedString(positions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
