/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.when_to_work.getPositionViewScheduling.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.when_to_work.getPositionViewScheduling.model.ResponseDatesEntryItem;
import java.util.ArrayList;
import java.util.List;
/**
 * RootResponse
 */

public class RootResponse {
  @JsonProperty("totalHours")
  private Integer totalHours = null;

  @JsonProperty("dates")
  private List<ResponseDatesEntryItem> dates = new ArrayList<>();

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("totalShifts")
  private Integer totalShifts = null;

  public RootResponse totalHours(Integer totalHours) {
    this.totalHours = totalHours;
    return this;
  }

   /**
   * Get totalHours
   * @return totalHours
  **/
  public Integer getTotalHours() {
    return totalHours;
  }

  public void setTotalHours(Integer totalHours) {
    this.totalHours = totalHours;
  }

  public RootResponse dates(List<ResponseDatesEntryItem> dates) {
    this.dates = dates;
    return this;
  }

  public RootResponse addDatesItem(ResponseDatesEntryItem datesItem) {
    this.dates.add(datesItem);
    return this;
  }

   /**
   * Get dates
   * @return dates
  **/
  public List<ResponseDatesEntryItem> getDates() {
    return dates;
  }

  public void setDates(List<ResponseDatesEntryItem> dates) {
    this.dates = dates;
  }

  public RootResponse title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public RootResponse totalShifts(Integer totalShifts) {
    this.totalShifts = totalShifts;
    return this;
  }

   /**
   * Get totalShifts
   * @return totalShifts
  **/
  public Integer getTotalShifts() {
    return totalShifts;
  }

  public void setTotalShifts(Integer totalShifts) {
    this.totalShifts = totalShifts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootResponse RootResponse = (RootResponse) o;
    return Objects.equals(this.totalHours, RootResponse.totalHours) &&
        Objects.equals(this.dates, RootResponse.dates) &&
        Objects.equals(this.title, RootResponse.title) &&
        Objects.equals(this.totalShifts, RootResponse.totalShifts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalHours, dates, title, totalShifts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootResponse {\n");
    
    sb.append("    totalHours: ").append(toIndentedString(totalHours)).append("\n");
    sb.append("    dates: ").append(toIndentedString(dates)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    totalShifts: ").append(toIndentedString(totalShifts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
