/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.when_to_work.scheduleList.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.when_to_work.scheduleList.model.ResponseShiftsEntryItem;
import java.util.ArrayList;
import java.util.List;
/**
 * Response5
 */

public class Response5 {
  @JsonProperty("date")
  private String date = null;

  @JsonProperty("shifts")
  private List<ResponseShiftsEntryItem> shifts = new ArrayList<>();

  public Response5 date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public Response5 shifts(List<ResponseShiftsEntryItem> shifts) {
    this.shifts = shifts;
    return this;
  }

  public Response5 addShiftsItem(ResponseShiftsEntryItem shiftsItem) {
    this.shifts.add(shiftsItem);
    return this;
  }

   /**
   * Get shifts
   * @return shifts
  **/
  public List<ResponseShiftsEntryItem> getShifts() {
    return shifts;
  }

  public void setShifts(List<ResponseShiftsEntryItem> shifts) {
    this.shifts = shifts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Response5 Response_5 = (Response5) o;
    return Objects.equals(this.date, Response_5.date) &&
        Objects.equals(this.shifts, Response_5.shifts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, shifts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Response5 {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    shifts: ").append(toIndentedString(shifts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
