/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.when_to_work.scheduleList.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.when_to_work.scheduleList.model.ResponseAvailablePositionsEntryItem;
import com.wavemaker.when_to_work.scheduleList.model.ResponseWeeklyShifts;
import java.util.ArrayList;
import java.util.List;
/**
 * ResponseRootResponseROOTEntryItem
 */

public class ResponseRootResponseROOTEntryItem {
  @JsonProperty("firstName")
  private String firstName = null;

  @JsonProperty("lastName")
  private String lastName = null;

  @JsonProperty("weeklyShifts")
  private ResponseWeeklyShifts weeklyShifts = null;

  @JsonProperty("shiftCount")
  private Integer shiftCount = null;

  @JsonProperty("totalHours")
  private Integer totalHours = null;

  @JsonProperty("availablePositions")
  private List<ResponseAvailablePositionsEntryItem> availablePositions = new ArrayList<>();

  @JsonProperty("phones")
  private List<String> phones = new ArrayList<>();

  @JsonProperty("employeeId")
  private Integer employeeId = null;

  public ResponseRootResponseROOTEntryItem firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public ResponseRootResponseROOTEntryItem lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public ResponseRootResponseROOTEntryItem weeklyShifts(ResponseWeeklyShifts weeklyShifts) {
    this.weeklyShifts = weeklyShifts;
    return this;
  }

   /**
   * Get weeklyShifts
   * @return weeklyShifts
  **/
  public ResponseWeeklyShifts getWeeklyShifts() {
    return weeklyShifts;
  }

  public void setWeeklyShifts(ResponseWeeklyShifts weeklyShifts) {
    this.weeklyShifts = weeklyShifts;
  }

  public ResponseRootResponseROOTEntryItem shiftCount(Integer shiftCount) {
    this.shiftCount = shiftCount;
    return this;
  }

   /**
   * Get shiftCount
   * @return shiftCount
  **/
  public Integer getShiftCount() {
    return shiftCount;
  }

  public void setShiftCount(Integer shiftCount) {
    this.shiftCount = shiftCount;
  }

  public ResponseRootResponseROOTEntryItem totalHours(Integer totalHours) {
    this.totalHours = totalHours;
    return this;
  }

   /**
   * Get totalHours
   * @return totalHours
  **/
  public Integer getTotalHours() {
    return totalHours;
  }

  public void setTotalHours(Integer totalHours) {
    this.totalHours = totalHours;
  }

  public ResponseRootResponseROOTEntryItem availablePositions(List<ResponseAvailablePositionsEntryItem> availablePositions) {
    this.availablePositions = availablePositions;
    return this;
  }

  public ResponseRootResponseROOTEntryItem addAvailablePositionsItem(ResponseAvailablePositionsEntryItem availablePositionsItem) {
    this.availablePositions.add(availablePositionsItem);
    return this;
  }

   /**
   * Get availablePositions
   * @return availablePositions
  **/
  public List<ResponseAvailablePositionsEntryItem> getAvailablePositions() {
    return availablePositions;
  }

  public void setAvailablePositions(List<ResponseAvailablePositionsEntryItem> availablePositions) {
    this.availablePositions = availablePositions;
  }

  public ResponseRootResponseROOTEntryItem phones(List<String> phones) {
    this.phones = phones;
    return this;
  }

  public ResponseRootResponseROOTEntryItem addPhonesItem(String phonesItem) {
    this.phones.add(phonesItem);
    return this;
  }

   /**
   * Get phones
   * @return phones
  **/
  public List<String> getPhones() {
    return phones;
  }

  public void setPhones(List<String> phones) {
    this.phones = phones;
  }

  public ResponseRootResponseROOTEntryItem employeeId(Integer employeeId) {
    this.employeeId = employeeId;
    return this;
  }

   /**
   * Get employeeId
   * @return employeeId
  **/
  public Integer getEmployeeId() {
    return employeeId;
  }

  public void setEmployeeId(Integer employeeId) {
    this.employeeId = employeeId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRootResponseROOTEntryItem Response_RootResponseROOTEntryItem = (ResponseRootResponseROOTEntryItem) o;
    return Objects.equals(this.firstName, Response_RootResponseROOTEntryItem.firstName) &&
        Objects.equals(this.lastName, Response_RootResponseROOTEntryItem.lastName) &&
        Objects.equals(this.weeklyShifts, Response_RootResponseROOTEntryItem.weeklyShifts) &&
        Objects.equals(this.shiftCount, Response_RootResponseROOTEntryItem.shiftCount) &&
        Objects.equals(this.totalHours, Response_RootResponseROOTEntryItem.totalHours) &&
        Objects.equals(this.availablePositions, Response_RootResponseROOTEntryItem.availablePositions) &&
        Objects.equals(this.phones, Response_RootResponseROOTEntryItem.phones) &&
        Objects.equals(this.employeeId, Response_RootResponseROOTEntryItem.employeeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstName, lastName, weeklyShifts, shiftCount, totalHours, availablePositions, phones, employeeId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRootResponseROOTEntryItem {\n");
    
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    weeklyShifts: ").append(toIndentedString(weeklyShifts)).append("\n");
    sb.append("    shiftCount: ").append(toIndentedString(shiftCount)).append("\n");
    sb.append("    totalHours: ").append(toIndentedString(totalHours)).append("\n");
    sb.append("    availablePositions: ").append(toIndentedString(availablePositions)).append("\n");
    sb.append("    phones: ").append(toIndentedString(phones)).append("\n");
    sb.append("    employeeId: ").append(toIndentedString(employeeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
