/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.when_to_work.dayPreferenceList.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * RequestPreferencesEntryItem
 */

public class RequestPreferencesEntryItem {
  @JsonProperty("date")
  private String date = null;

  @JsonProperty("companyId")
  private Integer companyId = null;

  @JsonProperty("editedBy")
  private Integer editedBy = null;

  @JsonProperty("employeeId")
  private Integer employeeId = null;

  @JsonProperty("compression")
  private Integer compression = null;

  @JsonProperty("isDayPrefs")
  private Boolean isDayPrefs = null;

  @JsonProperty("prefs")
  private String prefs = null;

  public RequestPreferencesEntryItem date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public RequestPreferencesEntryItem companyId(Integer companyId) {
    this.companyId = companyId;
    return this;
  }

   /**
   * Get companyId
   * @return companyId
  **/
  public Integer getCompanyId() {
    return companyId;
  }

  public void setCompanyId(Integer companyId) {
    this.companyId = companyId;
  }

  public RequestPreferencesEntryItem editedBy(Integer editedBy) {
    this.editedBy = editedBy;
    return this;
  }

   /**
   * Get editedBy
   * @return editedBy
  **/
  public Integer getEditedBy() {
    return editedBy;
  }

  public void setEditedBy(Integer editedBy) {
    this.editedBy = editedBy;
  }

  public RequestPreferencesEntryItem employeeId(Integer employeeId) {
    this.employeeId = employeeId;
    return this;
  }

   /**
   * Get employeeId
   * @return employeeId
  **/
  public Integer getEmployeeId() {
    return employeeId;
  }

  public void setEmployeeId(Integer employeeId) {
    this.employeeId = employeeId;
  }

  public RequestPreferencesEntryItem compression(Integer compression) {
    this.compression = compression;
    return this;
  }

   /**
   * Get compression
   * @return compression
  **/
  public Integer getCompression() {
    return compression;
  }

  public void setCompression(Integer compression) {
    this.compression = compression;
  }

  public RequestPreferencesEntryItem isDayPrefs(Boolean isDayPrefs) {
    this.isDayPrefs = isDayPrefs;
    return this;
  }

   /**
   * Get isDayPrefs
   * @return isDayPrefs
  **/
  public Boolean isIsDayPrefs() {
    return isDayPrefs;
  }

  public void setIsDayPrefs(Boolean isDayPrefs) {
    this.isDayPrefs = isDayPrefs;
  }

  public RequestPreferencesEntryItem prefs(String prefs) {
    this.prefs = prefs;
    return this;
  }

   /**
   * Get prefs
   * @return prefs
  **/
  public String getPrefs() {
    return prefs;
  }

  public void setPrefs(String prefs) {
    this.prefs = prefs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestPreferencesEntryItem Request_preferencesEntryItem = (RequestPreferencesEntryItem) o;
    return Objects.equals(this.date, Request_preferencesEntryItem.date) &&
        Objects.equals(this.companyId, Request_preferencesEntryItem.companyId) &&
        Objects.equals(this.editedBy, Request_preferencesEntryItem.editedBy) &&
        Objects.equals(this.employeeId, Request_preferencesEntryItem.employeeId) &&
        Objects.equals(this.compression, Request_preferencesEntryItem.compression) &&
        Objects.equals(this.isDayPrefs, Request_preferencesEntryItem.isDayPrefs) &&
        Objects.equals(this.prefs, Request_preferencesEntryItem.prefs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, companyId, editedBy, employeeId, compression, isDayPrefs, prefs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestPreferencesEntryItem {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    editedBy: ").append(toIndentedString(editedBy)).append("\n");
    sb.append("    employeeId: ").append(toIndentedString(employeeId)).append("\n");
    sb.append("    compression: ").append(toIndentedString(compression)).append("\n");
    sb.append("    isDayPrefs: ").append(toIndentedString(isDayPrefs)).append("\n");
    sb.append("    prefs: ").append(toIndentedString(prefs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
