/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.when_to_work.dayPreferenceList.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.when_to_work.dayPreferenceList.model.RequestPreferencesEntryItem;
import java.util.ArrayList;
import java.util.List;
/**
 * RootRequest
 */

public class RootRequest {
  @JsonProperty("preferences")
  private List<RequestPreferencesEntryItem> preferences = new ArrayList<>();

  public RootRequest preferences(List<RequestPreferencesEntryItem> preferences) {
    this.preferences = preferences;
    return this;
  }

  public RootRequest addPreferencesItem(RequestPreferencesEntryItem preferencesItem) {
    this.preferences.add(preferencesItem);
    return this;
  }

   /**
   * Get preferences
   * @return preferences
  **/
  public List<RequestPreferencesEntryItem> getPreferences() {
    return preferences;
  }

  public void setPreferences(List<RequestPreferencesEntryItem> preferences) {
    this.preferences = preferences;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootRequest RootRequest = (RootRequest) o;
    return Objects.equals(this.preferences, RootRequest.preferences);
  }

  @Override
  public int hashCode() {
    return Objects.hash(preferences);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootRequest {\n");
    
    sb.append("    preferences: ").append(toIndentedString(preferences)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
