/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.when_to_work.requestTimeOff.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * RootResponse
 */

public class RootResponse {
  @JsonProperty("comments")
  private String comments = null;

  @JsonProperty("endDate")
  private String endDate = null;

  @JsonProperty("endDateTimes")
  private String endDateTimes = null;

  @JsonProperty("requestedAt")
  private String requestedAt = null;

  @JsonProperty("requestId")
  private Integer requestId = null;

  @JsonProperty("repeatSummary")
  private String repeatSummary = null;

  @JsonProperty("employeeId")
  private Integer employeeId = null;

  @JsonProperty("startTime")
  private String startTime = null;

  @JsonProperty("endTime")
  private String endTime = null;

  @JsonProperty("startDate")
  private String startDate = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("canCancel")
  private Boolean canCancel = null;

  public RootResponse comments(String comments) {
    this.comments = comments;
    return this;
  }

   /**
   * Get comments
   * @return comments
  **/
  public String getComments() {
    return comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

  public RootResponse endDate(String endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  public String getEndDate() {
    return endDate;
  }

  public void setEndDate(String endDate) {
    this.endDate = endDate;
  }

  public RootResponse endDateTimes(String endDateTimes) {
    this.endDateTimes = endDateTimes;
    return this;
  }

   /**
   * Get endDateTimes
   * @return endDateTimes
  **/
  public String getEndDateTimes() {
    return endDateTimes;
  }

  public void setEndDateTimes(String endDateTimes) {
    this.endDateTimes = endDateTimes;
  }

  public RootResponse requestedAt(String requestedAt) {
    this.requestedAt = requestedAt;
    return this;
  }

   /**
   * Get requestedAt
   * @return requestedAt
  **/
  public String getRequestedAt() {
    return requestedAt;
  }

  public void setRequestedAt(String requestedAt) {
    this.requestedAt = requestedAt;
  }

  public RootResponse requestId(Integer requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * Get requestId
   * @return requestId
  **/
  public Integer getRequestId() {
    return requestId;
  }

  public void setRequestId(Integer requestId) {
    this.requestId = requestId;
  }

  public RootResponse repeatSummary(String repeatSummary) {
    this.repeatSummary = repeatSummary;
    return this;
  }

   /**
   * Get repeatSummary
   * @return repeatSummary
  **/
  public String getRepeatSummary() {
    return repeatSummary;
  }

  public void setRepeatSummary(String repeatSummary) {
    this.repeatSummary = repeatSummary;
  }

  public RootResponse employeeId(Integer employeeId) {
    this.employeeId = employeeId;
    return this;
  }

   /**
   * Get employeeId
   * @return employeeId
  **/
  public Integer getEmployeeId() {
    return employeeId;
  }

  public void setEmployeeId(Integer employeeId) {
    this.employeeId = employeeId;
  }

  public RootResponse startTime(String startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  public String getStartTime() {
    return startTime;
  }

  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }

  public RootResponse endTime(String endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  public String getEndTime() {
    return endTime;
  }

  public void setEndTime(String endTime) {
    this.endTime = endTime;
  }

  public RootResponse startDate(String startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  public String getStartDate() {
    return startDate;
  }

  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }

  public RootResponse status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public RootResponse canCancel(Boolean canCancel) {
    this.canCancel = canCancel;
    return this;
  }

   /**
   * Get canCancel
   * @return canCancel
  **/
  public Boolean isCanCancel() {
    return canCancel;
  }

  public void setCanCancel(Boolean canCancel) {
    this.canCancel = canCancel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootResponse RootResponse = (RootResponse) o;
    return Objects.equals(this.comments, RootResponse.comments) &&
        Objects.equals(this.endDate, RootResponse.endDate) &&
        Objects.equals(this.endDateTimes, RootResponse.endDateTimes) &&
        Objects.equals(this.requestedAt, RootResponse.requestedAt) &&
        Objects.equals(this.requestId, RootResponse.requestId) &&
        Objects.equals(this.repeatSummary, RootResponse.repeatSummary) &&
        Objects.equals(this.employeeId, RootResponse.employeeId) &&
        Objects.equals(this.startTime, RootResponse.startTime) &&
        Objects.equals(this.endTime, RootResponse.endTime) &&
        Objects.equals(this.startDate, RootResponse.startDate) &&
        Objects.equals(this.status, RootResponse.status) &&
        Objects.equals(this.canCancel, RootResponse.canCancel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(comments, endDate, endDateTimes, requestedAt, requestId, repeatSummary, employeeId, startTime, endTime, startDate, status, canCancel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootResponse {\n");
    
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    endDateTimes: ").append(toIndentedString(endDateTimes)).append("\n");
    sb.append("    requestedAt: ").append(toIndentedString(requestedAt)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    repeatSummary: ").append(toIndentedString(repeatSummary)).append("\n");
    sb.append("    employeeId: ").append(toIndentedString(employeeId)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    canCancel: ").append(toIndentedString(canCancel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
