/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.when_to_work.getTenants.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseRootResponseROOTEntryItem
 */

public class ResponseRootResponseROOTEntryItem {
  @JsonProperty("departmentName")
  private String departmentName = null;

  @JsonProperty("address")
  private String address = null;

  @JsonProperty("dropDead")
  private String dropDead = null;

  @JsonProperty("priceTable")
  private String priceTable = null;

  @JsonProperty("city")
  private String city = null;

  @JsonProperty("timezone")
  private String timezone = null;

  @JsonProperty("companyName")
  private String companyName = null;

  @JsonProperty("trialStart")
  private String trialStart = null;

  @JsonProperty("companyId")
  private Integer companyId = null;

  @JsonProperty("weekStartDay")
  private Integer weekStartDay = null;

  @JsonProperty("tos")
  private String tos = null;

  @JsonProperty("state")
  private String state = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("timestamp")
  private String timestamp = null;

  public ResponseRootResponseROOTEntryItem departmentName(String departmentName) {
    this.departmentName = departmentName;
    return this;
  }

   /**
   * Get departmentName
   * @return departmentName
  **/
  public String getDepartmentName() {
    return departmentName;
  }

  public void setDepartmentName(String departmentName) {
    this.departmentName = departmentName;
  }

  public ResponseRootResponseROOTEntryItem address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public ResponseRootResponseROOTEntryItem dropDead(String dropDead) {
    this.dropDead = dropDead;
    return this;
  }

   /**
   * Get dropDead
   * @return dropDead
  **/
  public String getDropDead() {
    return dropDead;
  }

  public void setDropDead(String dropDead) {
    this.dropDead = dropDead;
  }

  public ResponseRootResponseROOTEntryItem priceTable(String priceTable) {
    this.priceTable = priceTable;
    return this;
  }

   /**
   * Get priceTable
   * @return priceTable
  **/
  public String getPriceTable() {
    return priceTable;
  }

  public void setPriceTable(String priceTable) {
    this.priceTable = priceTable;
  }

  public ResponseRootResponseROOTEntryItem city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public ResponseRootResponseROOTEntryItem timezone(String timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * Get timezone
   * @return timezone
  **/
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }

  public ResponseRootResponseROOTEntryItem companyName(String companyName) {
    this.companyName = companyName;
    return this;
  }

   /**
   * Get companyName
   * @return companyName
  **/
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }

  public ResponseRootResponseROOTEntryItem trialStart(String trialStart) {
    this.trialStart = trialStart;
    return this;
  }

   /**
   * Get trialStart
   * @return trialStart
  **/
  public String getTrialStart() {
    return trialStart;
  }

  public void setTrialStart(String trialStart) {
    this.trialStart = trialStart;
  }

  public ResponseRootResponseROOTEntryItem companyId(Integer companyId) {
    this.companyId = companyId;
    return this;
  }

   /**
   * Get companyId
   * @return companyId
  **/
  public Integer getCompanyId() {
    return companyId;
  }

  public void setCompanyId(Integer companyId) {
    this.companyId = companyId;
  }

  public ResponseRootResponseROOTEntryItem weekStartDay(Integer weekStartDay) {
    this.weekStartDay = weekStartDay;
    return this;
  }

   /**
   * Get weekStartDay
   * @return weekStartDay
  **/
  public Integer getWeekStartDay() {
    return weekStartDay;
  }

  public void setWeekStartDay(Integer weekStartDay) {
    this.weekStartDay = weekStartDay;
  }

  public ResponseRootResponseROOTEntryItem tos(String tos) {
    this.tos = tos;
    return this;
  }

   /**
   * Get tos
   * @return tos
  **/
  public String getTos() {
    return tos;
  }

  public void setTos(String tos) {
    this.tos = tos;
  }

  public ResponseRootResponseROOTEntryItem state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public ResponseRootResponseROOTEntryItem status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public ResponseRootResponseROOTEntryItem timestamp(String timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  public String getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(String timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRootResponseROOTEntryItem Response_RootResponseROOTEntryItem = (ResponseRootResponseROOTEntryItem) o;
    return Objects.equals(this.departmentName, Response_RootResponseROOTEntryItem.departmentName) &&
        Objects.equals(this.address, Response_RootResponseROOTEntryItem.address) &&
        Objects.equals(this.dropDead, Response_RootResponseROOTEntryItem.dropDead) &&
        Objects.equals(this.priceTable, Response_RootResponseROOTEntryItem.priceTable) &&
        Objects.equals(this.city, Response_RootResponseROOTEntryItem.city) &&
        Objects.equals(this.timezone, Response_RootResponseROOTEntryItem.timezone) &&
        Objects.equals(this.companyName, Response_RootResponseROOTEntryItem.companyName) &&
        Objects.equals(this.trialStart, Response_RootResponseROOTEntryItem.trialStart) &&
        Objects.equals(this.companyId, Response_RootResponseROOTEntryItem.companyId) &&
        Objects.equals(this.weekStartDay, Response_RootResponseROOTEntryItem.weekStartDay) &&
        Objects.equals(this.tos, Response_RootResponseROOTEntryItem.tos) &&
        Objects.equals(this.state, Response_RootResponseROOTEntryItem.state) &&
        Objects.equals(this.status, Response_RootResponseROOTEntryItem.status) &&
        Objects.equals(this.timestamp, Response_RootResponseROOTEntryItem.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(departmentName, address, dropDead, priceTable, city, timezone, companyName, trialStart, companyId, weekStartDay, tos, state, status, timestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRootResponseROOTEntryItem {\n");
    
    sb.append("    departmentName: ").append(toIndentedString(departmentName)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    dropDead: ").append(toIndentedString(dropDead)).append("\n");
    sb.append("    priceTable: ").append(toIndentedString(priceTable)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    trialStart: ").append(toIndentedString(trialStart)).append("\n");
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    weekStartDay: ").append(toIndentedString(weekStartDay)).append("\n");
    sb.append("    tos: ").append(toIndentedString(tos)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
