/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.time.LocalDateTime;
import java.util.Objects;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Company generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`company`")
public class Company implements Serializable {

    private Integer companyId;
    private String companyName;
    private String departmentName;
    private String address;
    private String city;
    private String state;
    private LocalDateTime timestamp;
    private BigDecimal timezone;
    private String status;
    private Date trialStart;
    private Date dropDead;
    private Integer priceTable;
    private String tos;

    @Id
    @Column(name = "`company_id`", nullable = false, scale = 0, precision = 10)
    public Integer getCompanyId() {
        return this.companyId;
    }

    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    @Column(name = "`company_name`", nullable = true, length = 255)
    public String getCompanyName() {
        return this.companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    @Column(name = "`department_name`", nullable = true, length = 255)
    public String getDepartmentName() {
        return this.departmentName;
    }

    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    @Column(name = "`address`", nullable = true, length = 255)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "`city`", nullable = true, length = 255)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Column(name = "`state`", nullable = true, length = 255)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "`timestamp`", nullable = true)
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    @Column(name = "`timezone`", nullable = true, scale = 17, precision = 17)
    public BigDecimal getTimezone() {
        return this.timezone;
    }

    public void setTimezone(BigDecimal timezone) {
        this.timezone = timezone;
    }

    @Column(name = "`status`", nullable = true, length = 255)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "`trial_start`", nullable = true)
    public Date getTrialStart() {
        return this.trialStart;
    }

    public void setTrialStart(Date trialStart) {
        this.trialStart = trialStart;
    }

    @Column(name = "`drop_dead`", nullable = true)
    public Date getDropDead() {
        return this.dropDead;
    }

    public void setDropDead(Date dropDead) {
        this.dropDead = dropDead;
    }

    @Column(name = "`price_table`", nullable = true, scale = 0, precision = 10)
    public Integer getPriceTable() {
        return this.priceTable;
    }

    public void setPriceTable(Integer priceTable) {
        this.priceTable = priceTable;
    }

    @Column(name = "`tos`", nullable = true, length = 255)
    public String getTos() {
        return this.tos;
    }

    public void setTos(String tos) {
        this.tos = tos;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Company)) return false;
        final Company company = (Company) o;
        return Objects.equals(getCompanyId(), company.getCompanyId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCompanyId());
    }
}
