/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * EmployeePhone generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`employee_phone`")
@IdClass(EmployeePhoneId.class)
public class EmployeePhone implements Serializable {

    private Integer employeeId;
    private Integer sortOrder;
    private String phoneNumber;
    private Employee employee;

    @Id
    @Column(name = "`employee_id`", nullable = false, scale = 0, precision = 10)
    public Integer getEmployeeId() {
        return this.employeeId;
    }

    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    @Id
    @Column(name = "`sort_order`", nullable = false, scale = 0, precision = 10)
    public Integer getSortOrder() {
        return this.sortOrder;
    }

    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    @Column(name = "`phone_number`", nullable = false, length = 2147483647)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`employee_id`", referencedColumnName = "`employee_id`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`employee_phone_employee_id_fkey`"))
    @Fetch(FetchMode.JOIN)
    public Employee getEmployee() {
        return this.employee;
    }

    public void setEmployee(Employee employee) {
        if(employee != null) {
            this.employeeId = employee.getEmployeeId();
        }

        this.employee = employee;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EmployeePhone)) return false;
        final EmployeePhone employeePhone = (EmployeePhone) o;
        return Objects.equals(getEmployeeId(), employeePhone.getEmployeeId()) &&
                Objects.equals(getSortOrder(), employeePhone.getSortOrder());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmployeeId(),
                getSortOrder());
    }
}
