/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class EmployeeSkillId implements Serializable {

    private Integer employeeId;
    private Integer skillId;

    public Integer getEmployeeId() {
        return this.employeeId;
    }

    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    public Integer getSkillId() {
        return this.skillId;
    }

    public void setSkillId(Integer skillId) {
        this.skillId = skillId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EmployeeSkill)) return false;
        final EmployeeSkill employeeSkill = (EmployeeSkill) o;
        return Objects.equals(getEmployeeId(), employeeSkill.getEmployeeId()) &&
                Objects.equals(getSkillId(), employeeSkill.getSkillId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmployeeId(),
                getSkillId());
    }
}
