/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.Objects;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * EmployeeSkill generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`employee_skill`")
@IdClass(EmployeeSkillId.class)
public class EmployeeSkill implements Serializable {

    private Integer employeeId;
    private Integer skillId;
    private Integer suitabilityLevel;
    private String preference;
    private BigDecimal payRate;
    private Date certDate;
    private Employee employee;
    private Skill skill;

    @Id
    @Column(name = "`employee_id`", nullable = false, scale = 0, precision = 10)
    public Integer getEmployeeId() {
        return this.employeeId;
    }

    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    @Id
    @Column(name = "`skill_id`", nullable = false, scale = 0, precision = 10)
    public Integer getSkillId() {
        return this.skillId;
    }

    public void setSkillId(Integer skillId) {
        this.skillId = skillId;
    }

    @Column(name = "`suitability_level`", nullable = true, scale = 0, precision = 10)
    public Integer getSuitabilityLevel() {
        return this.suitabilityLevel;
    }

    public void setSuitabilityLevel(Integer suitabilityLevel) {
        this.suitabilityLevel = suitabilityLevel;
    }

    @Column(name = "`preference`", nullable = true, length = 255)
    public String getPreference() {
        return this.preference;
    }

    public void setPreference(String preference) {
        this.preference = preference;
    }

    @Column(name = "`pay_rate`", nullable = true, scale = 17, precision = 17)
    public BigDecimal getPayRate() {
        return this.payRate;
    }

    public void setPayRate(BigDecimal payRate) {
        this.payRate = payRate;
    }

    @Column(name = "`cert_date`", nullable = true)
    public Date getCertDate() {
        return this.certDate;
    }

    public void setCertDate(Date certDate) {
        this.certDate = certDate;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`employee_id`", referencedColumnName = "`employee_id`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`employee_skill_employee_id_fkey`"))
    @Fetch(FetchMode.JOIN)
    public Employee getEmployee() {
        return this.employee;
    }

    public void setEmployee(Employee employee) {
        if(employee != null) {
            this.employeeId = employee.getEmployeeId();
        }

        this.employee = employee;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`skill_id`", referencedColumnName = "`skill_id`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`employee_skill_skill_id_fkey`"))
    @Fetch(FetchMode.JOIN)
    public Skill getSkill() {
        return this.skill;
    }

    public void setSkill(Skill skill) {
        if(skill != null) {
            this.skillId = skill.getSkillId();
        }

        this.skill = skill;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EmployeeSkill)) return false;
        final EmployeeSkill employeeSkill = (EmployeeSkill) o;
        return Objects.equals(getEmployeeId(), employeeSkill.getEmployeeId()) &&
                Objects.equals(getSkillId(), employeeSkill.getSkillId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmployeeId(),
                getSkillId());
    }
}
