/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * FlywaySchemaHistory generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`flyway_schema_history`")
public class FlywaySchemaHistory implements Serializable {

    private Integer installedRank;
    private String version;
    private String description;
    private String type;
    private String script;
    private Integer checksum;
    private String installedBy;
    private LocalDateTime installedOn;
    private int executionTime;
    private boolean success;

    @Id
    @Column(name = "`installed_rank`", nullable = false, scale = 0, precision = 10)
    public Integer getInstalledRank() {
        return this.installedRank;
    }

    public void setInstalledRank(Integer installedRank) {
        this.installedRank = installedRank;
    }

    @Column(name = "`version`", nullable = true, length = 50)
    public String getVersion() {
        return this.version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    @Column(name = "`description`", nullable = false, length = 200)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "`type`", nullable = false, length = 20)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "`script`", nullable = false, length = 1000)
    public String getScript() {
        return this.script;
    }

    public void setScript(String script) {
        this.script = script;
    }

    @Column(name = "`checksum`", nullable = true, scale = 0, precision = 10)
    public Integer getChecksum() {
        return this.checksum;
    }

    public void setChecksum(Integer checksum) {
        this.checksum = checksum;
    }

    @Column(name = "`installed_by`", nullable = false, length = 100)
    public String getInstalledBy() {
        return this.installedBy;
    }

    public void setInstalledBy(String installedBy) {
        this.installedBy = installedBy;
    }

    @Column(name = "`installed_on`", nullable = false)
    public LocalDateTime getInstalledOn() {
        return this.installedOn;
    }

    public void setInstalledOn(LocalDateTime installedOn) {
        this.installedOn = installedOn;
    }

    @Column(name = "`execution_time`", nullable = false, scale = 0, precision = 10)
    public int getExecutionTime() {
        return this.executionTime;
    }

    public void setExecutionTime(int executionTime) {
        this.executionTime = executionTime;
    }

    @Column(name = "`success`", nullable = false)
    public boolean isSuccess() {
        return this.success;
    }

    public void setSuccess(boolean success) {
        this.success = success;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof FlywaySchemaHistory)) return false;
        final FlywaySchemaHistory flywaySchemaHistory = (FlywaySchemaHistory) o;
        return Objects.equals(getInstalledRank(), flywaySchemaHistory.getInstalledRank());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getInstalledRank());
    }
}
