/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * GroupSkill generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`group_skill`")
@IdClass(GroupSkillId.class)
public class GroupSkill implements Serializable {

    private Integer groupId;
    private Integer skillId;
    private SkillGroup skillGroup;
    private Skill skill;

    @Id
    @Column(name = "`group_id`", nullable = false, scale = 0, precision = 10)
    public Integer getGroupId() {
        return this.groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    @Id
    @Column(name = "`skill_id`", nullable = false, scale = 0, precision = 10)
    public Integer getSkillId() {
        return this.skillId;
    }

    public void setSkillId(Integer skillId) {
        this.skillId = skillId;
    }


    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`group_id`", referencedColumnName = "`group_id`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`group_skill_group_id_fkey`"))
    @Fetch(FetchMode.JOIN)
    public SkillGroup getSkillGroup() {
        return this.skillGroup;
    }

    public void setSkillGroup(SkillGroup skillGroup) {
        if(skillGroup != null) {
            this.groupId = skillGroup.getGroupId();
        }

        this.skillGroup = skillGroup;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`skill_id`", referencedColumnName = "`skill_id`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`group_skill_skill_id_fkey`"))
    @Fetch(FetchMode.JOIN)
    public Skill getSkill() {
        return this.skill;
    }

    public void setSkill(Skill skill) {
        if(skill != null) {
            this.skillId = skill.getSkillId();
        }

        this.skill = skill;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GroupSkill)) return false;
        final GroupSkill groupSkill = (GroupSkill) o;
        return Objects.equals(getGroupId(), groupSkill.getGroupId()) &&
                Objects.equals(getSkillId(), groupSkill.getSkillId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getGroupId(),
                getSkillId());
    }
}
