/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class GroupSkillId implements Serializable {

    private Integer groupId;
    private Integer skillId;

    public Integer getGroupId() {
        return this.groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    public Integer getSkillId() {
        return this.skillId;
    }

    public void setSkillId(Integer skillId) {
        this.skillId = skillId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GroupSkill)) return false;
        final GroupSkill groupSkill = (GroupSkill) o;
        return Objects.equals(getGroupId(), groupSkill.getGroupId()) &&
                Objects.equals(getSkillId(), groupSkill.getSkillId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getGroupId(),
                getSkillId());
    }
}
