/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * GroupCat generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`group_cat`")
@IdClass(GroupCatId.class)
public class GroupCat implements Serializable {

    private Integer groupId;
    private Integer catId;
    private Category category;
    private CatGroup catGroup;

    @Id
    @Column(name = "`group_id`", nullable = false, scale = 0, precision = 10)
    public Integer getGroupId() {
        return this.groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    @Id
    @Column(name = "`cat_id`", nullable = false, scale = 0, precision = 10)
    public Integer getCatId() {
        return this.catId;
    }

    public void setCatId(Integer catId) {
        this.catId = catId;
    }


    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`cat_id`", referencedColumnName = "`category_id`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`group_cat_cat_id_fkey`"))
    @Fetch(FetchMode.JOIN)
    public Category getCategory() {
        return this.category;
    }

    public void setCategory(Category category) {
        if(category != null) {
            this.catId = category.getCategoryId();
        }

        this.category = category;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`group_id`", referencedColumnName = "`group_id`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`group_cat_group_id_fkey`"))
    @Fetch(FetchMode.JOIN)
    public CatGroup getCatGroup() {
        return this.catGroup;
    }

    public void setCatGroup(CatGroup catGroup) {
        if(catGroup != null) {
            this.groupId = catGroup.getGroupId();
        }

        this.catGroup = catGroup;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GroupCat)) return false;
        final GroupCat groupCat = (GroupCat) o;
        return Objects.equals(getGroupId(), groupCat.getGroupId()) &&
                Objects.equals(getCatId(), groupCat.getCatId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getGroupId(),
                getCatId());
    }
}
