app.build.ui.mode=${build.ui.mode}
app.build.ui.ng.config=${build.ui.ng.config}
app.build.ui.spa.enabled=true
app.contextPath=""
app.serverPath="http://localhost:8080"
build.ui.mode=react
build.ui.ng.config=--c=production
build.ui.node.args=--max-old-space-size=1024
app.contextPath=""
app.serverPath="https://when-to-work.onwavemaker.com"
