/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.when_to_work.AddEmployee.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.when_to_work.AddEmployee.model.RequestAddress;
import java.util.ArrayList;
import java.util.List;
/**
 * RootRequest
 */

public class RootRequest {
  @JsonProperty("maxScheduledHours")
  private Integer maxScheduledHours = null;

  @JsonProperty("lastName")
  private String lastName = null;

  @JsonProperty("hireDate")
  private String hireDate = null;

  @JsonProperty("address")
  private RequestAddress address = null;

  @JsonProperty("comments")
  private String comments = null;

  @JsonProperty("maxDailyHours")
  private Integer maxDailyHours = null;

  @JsonProperty("customField1")
  private String customField1 = null;

  @JsonProperty("employeePhoto")
  private String employeePhoto = null;

  @JsonProperty("customField2")
  private String customField2 = null;

  @JsonProperty("payRate")
  private Double payRate = null;

  @JsonProperty("priorityGroup")
  private String priorityGroup = null;

  @JsonProperty("phones")
  private List<String> phones = new ArrayList<>();

  @JsonProperty("nextAlertDate")
  private String nextAlertDate = null;

  @JsonProperty("cell")
  private String cell = null;

  @JsonProperty("employeeNumber")
  private String employeeNumber = null;

  @JsonProperty("firstName")
  private String firstName = null;

  @JsonProperty("empTypeId")
  private Integer empTypeId = null;

  @JsonProperty("googleCalExport")
  private Boolean googleCalExport = null;

  @JsonProperty("maxWeeklyDays")
  private Integer maxWeeklyDays = null;

  @JsonProperty("maxDailyShifts")
  private Integer maxDailyShifts = null;

  @JsonProperty("email")
  private String email = null;

  public RootRequest maxScheduledHours(Integer maxScheduledHours) {
    this.maxScheduledHours = maxScheduledHours;
    return this;
  }

   /**
   * Get maxScheduledHours
   * @return maxScheduledHours
  **/
  public Integer getMaxScheduledHours() {
    return maxScheduledHours;
  }

  public void setMaxScheduledHours(Integer maxScheduledHours) {
    this.maxScheduledHours = maxScheduledHours;
  }

  public RootRequest lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public RootRequest hireDate(String hireDate) {
    this.hireDate = hireDate;
    return this;
  }

   /**
   * Get hireDate
   * @return hireDate
  **/
  public String getHireDate() {
    return hireDate;
  }

  public void setHireDate(String hireDate) {
    this.hireDate = hireDate;
  }

  public RootRequest address(RequestAddress address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  public RequestAddress getAddress() {
    return address;
  }

  public void setAddress(RequestAddress address) {
    this.address = address;
  }

  public RootRequest comments(String comments) {
    this.comments = comments;
    return this;
  }

   /**
   * Get comments
   * @return comments
  **/
  public String getComments() {
    return comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

  public RootRequest maxDailyHours(Integer maxDailyHours) {
    this.maxDailyHours = maxDailyHours;
    return this;
  }

   /**
   * Get maxDailyHours
   * @return maxDailyHours
  **/
  public Integer getMaxDailyHours() {
    return maxDailyHours;
  }

  public void setMaxDailyHours(Integer maxDailyHours) {
    this.maxDailyHours = maxDailyHours;
  }

  public RootRequest customField1(String customField1) {
    this.customField1 = customField1;
    return this;
  }

   /**
   * Get customField1
   * @return customField1
  **/
  public String getCustomField1() {
    return customField1;
  }

  public void setCustomField1(String customField1) {
    this.customField1 = customField1;
  }

  public RootRequest employeePhoto(String employeePhoto) {
    this.employeePhoto = employeePhoto;
    return this;
  }

   /**
   * Get employeePhoto
   * @return employeePhoto
  **/
  public String getEmployeePhoto() {
    return employeePhoto;
  }

  public void setEmployeePhoto(String employeePhoto) {
    this.employeePhoto = employeePhoto;
  }

  public RootRequest customField2(String customField2) {
    this.customField2 = customField2;
    return this;
  }

   /**
   * Get customField2
   * @return customField2
  **/
  public String getCustomField2() {
    return customField2;
  }

  public void setCustomField2(String customField2) {
    this.customField2 = customField2;
  }

  public RootRequest payRate(Double payRate) {
    this.payRate = payRate;
    return this;
  }

   /**
   * Get payRate
   * @return payRate
  **/
  public Double getPayRate() {
    return payRate;
  }

  public void setPayRate(Double payRate) {
    this.payRate = payRate;
  }

  public RootRequest priorityGroup(String priorityGroup) {
    this.priorityGroup = priorityGroup;
    return this;
  }

   /**
   * Get priorityGroup
   * @return priorityGroup
  **/
  public String getPriorityGroup() {
    return priorityGroup;
  }

  public void setPriorityGroup(String priorityGroup) {
    this.priorityGroup = priorityGroup;
  }

  public RootRequest phones(List<String> phones) {
    this.phones = phones;
    return this;
  }

  public RootRequest addPhonesItem(String phonesItem) {
    this.phones.add(phonesItem);
    return this;
  }

   /**
   * Get phones
   * @return phones
  **/
  public List<String> getPhones() {
    return phones;
  }

  public void setPhones(List<String> phones) {
    this.phones = phones;
  }

  public RootRequest nextAlertDate(String nextAlertDate) {
    this.nextAlertDate = nextAlertDate;
    return this;
  }

   /**
   * Get nextAlertDate
   * @return nextAlertDate
  **/
  public String getNextAlertDate() {
    return nextAlertDate;
  }

  public void setNextAlertDate(String nextAlertDate) {
    this.nextAlertDate = nextAlertDate;
  }

  public RootRequest cell(String cell) {
    this.cell = cell;
    return this;
  }

   /**
   * Get cell
   * @return cell
  **/
  public String getCell() {
    return cell;
  }

  public void setCell(String cell) {
    this.cell = cell;
  }

  public RootRequest employeeNumber(String employeeNumber) {
    this.employeeNumber = employeeNumber;
    return this;
  }

   /**
   * Get employeeNumber
   * @return employeeNumber
  **/
  public String getEmployeeNumber() {
    return employeeNumber;
  }

  public void setEmployeeNumber(String employeeNumber) {
    this.employeeNumber = employeeNumber;
  }

  public RootRequest firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public RootRequest empTypeId(Integer empTypeId) {
    this.empTypeId = empTypeId;
    return this;
  }

   /**
   * Get empTypeId
   * @return empTypeId
  **/
  public Integer getEmpTypeId() {
    return empTypeId;
  }

  public void setEmpTypeId(Integer empTypeId) {
    this.empTypeId = empTypeId;
  }

  public RootRequest googleCalExport(Boolean googleCalExport) {
    this.googleCalExport = googleCalExport;
    return this;
  }

   /**
   * Get googleCalExport
   * @return googleCalExport
  **/
  public Boolean isGoogleCalExport() {
    return googleCalExport;
  }

  public void setGoogleCalExport(Boolean googleCalExport) {
    this.googleCalExport = googleCalExport;
  }

  public RootRequest maxWeeklyDays(Integer maxWeeklyDays) {
    this.maxWeeklyDays = maxWeeklyDays;
    return this;
  }

   /**
   * Get maxWeeklyDays
   * @return maxWeeklyDays
  **/
  public Integer getMaxWeeklyDays() {
    return maxWeeklyDays;
  }

  public void setMaxWeeklyDays(Integer maxWeeklyDays) {
    this.maxWeeklyDays = maxWeeklyDays;
  }

  public RootRequest maxDailyShifts(Integer maxDailyShifts) {
    this.maxDailyShifts = maxDailyShifts;
    return this;
  }

   /**
   * Get maxDailyShifts
   * @return maxDailyShifts
  **/
  public Integer getMaxDailyShifts() {
    return maxDailyShifts;
  }

  public void setMaxDailyShifts(Integer maxDailyShifts) {
    this.maxDailyShifts = maxDailyShifts;
  }

  public RootRequest email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootRequest RootRequest = (RootRequest) o;
    return Objects.equals(this.maxScheduledHours, RootRequest.maxScheduledHours) &&
        Objects.equals(this.lastName, RootRequest.lastName) &&
        Objects.equals(this.hireDate, RootRequest.hireDate) &&
        Objects.equals(this.address, RootRequest.address) &&
        Objects.equals(this.comments, RootRequest.comments) &&
        Objects.equals(this.maxDailyHours, RootRequest.maxDailyHours) &&
        Objects.equals(this.customField1, RootRequest.customField1) &&
        Objects.equals(this.employeePhoto, RootRequest.employeePhoto) &&
        Objects.equals(this.customField2, RootRequest.customField2) &&
        Objects.equals(this.payRate, RootRequest.payRate) &&
        Objects.equals(this.priorityGroup, RootRequest.priorityGroup) &&
        Objects.equals(this.phones, RootRequest.phones) &&
        Objects.equals(this.nextAlertDate, RootRequest.nextAlertDate) &&
        Objects.equals(this.cell, RootRequest.cell) &&
        Objects.equals(this.employeeNumber, RootRequest.employeeNumber) &&
        Objects.equals(this.firstName, RootRequest.firstName) &&
        Objects.equals(this.empTypeId, RootRequest.empTypeId) &&
        Objects.equals(this.googleCalExport, RootRequest.googleCalExport) &&
        Objects.equals(this.maxWeeklyDays, RootRequest.maxWeeklyDays) &&
        Objects.equals(this.maxDailyShifts, RootRequest.maxDailyShifts) &&
        Objects.equals(this.email, RootRequest.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxScheduledHours, lastName, hireDate, address, comments, maxDailyHours, customField1, employeePhoto, customField2, payRate, priorityGroup, phones, nextAlertDate, cell, employeeNumber, firstName, empTypeId, googleCalExport, maxWeeklyDays, maxDailyShifts, email);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootRequest {\n");
    
    sb.append("    maxScheduledHours: ").append(toIndentedString(maxScheduledHours)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    hireDate: ").append(toIndentedString(hireDate)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    maxDailyHours: ").append(toIndentedString(maxDailyHours)).append("\n");
    sb.append("    customField1: ").append(toIndentedString(customField1)).append("\n");
    sb.append("    employeePhoto: ").append(toIndentedString(employeePhoto)).append("\n");
    sb.append("    customField2: ").append(toIndentedString(customField2)).append("\n");
    sb.append("    payRate: ").append(toIndentedString(payRate)).append("\n");
    sb.append("    priorityGroup: ").append(toIndentedString(priorityGroup)).append("\n");
    sb.append("    phones: ").append(toIndentedString(phones)).append("\n");
    sb.append("    nextAlertDate: ").append(toIndentedString(nextAlertDate)).append("\n");
    sb.append("    cell: ").append(toIndentedString(cell)).append("\n");
    sb.append("    employeeNumber: ").append(toIndentedString(employeeNumber)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    empTypeId: ").append(toIndentedString(empTypeId)).append("\n");
    sb.append("    googleCalExport: ").append(toIndentedString(googleCalExport)).append("\n");
    sb.append("    maxWeeklyDays: ").append(toIndentedString(maxWeeklyDays)).append("\n");
    sb.append("    maxDailyShifts: ").append(toIndentedString(maxDailyShifts)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
