/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.when_to_work.calendarShiftTimingView.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.when_to_work.calendarShiftTimingView.model.ResponseShiftGroupsEntryItem;
import java.util.ArrayList;
import java.util.List;
/**
 * ResponseDatesEntryItem
 */

public class ResponseDatesEntryItem {
  @JsonProperty("date")
  private String date = null;

  @JsonProperty("shiftGroups")
  private List<ResponseShiftGroupsEntryItem> shiftGroups = new ArrayList<>();

  public ResponseDatesEntryItem date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public ResponseDatesEntryItem shiftGroups(List<ResponseShiftGroupsEntryItem> shiftGroups) {
    this.shiftGroups = shiftGroups;
    return this;
  }

  public ResponseDatesEntryItem addShiftGroupsItem(ResponseShiftGroupsEntryItem shiftGroupsItem) {
    this.shiftGroups.add(shiftGroupsItem);
    return this;
  }

   /**
   * Get shiftGroups
   * @return shiftGroups
  **/
  public List<ResponseShiftGroupsEntryItem> getShiftGroups() {
    return shiftGroups;
  }

  public void setShiftGroups(List<ResponseShiftGroupsEntryItem> shiftGroups) {
    this.shiftGroups = shiftGroups;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseDatesEntryItem Response_datesEntryItem = (ResponseDatesEntryItem) o;
    return Objects.equals(this.date, Response_datesEntryItem.date) &&
        Objects.equals(this.shiftGroups, Response_datesEntryItem.shiftGroups);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, shiftGroups);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseDatesEntryItem {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    shiftGroups: ").append(toIndentedString(shiftGroups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
