/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.when_to_work.addManager.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.when_to_work.addManager.model.JavaLangObject;
import java.util.ArrayList;
import java.util.List;
/**
 * ResponseEmployee
 */

public class ResponseEmployee {
  @JsonProperty("maxScheduledHours")
  private String maxScheduledHours = null;

  @JsonProperty("lastName")
  private String lastName = null;

  @JsonProperty("hireDate")
  private String hireDate = null;

  @JsonProperty("logonCount")
  private String logonCount = null;

  @JsonProperty("maxDailyHours")
  private String maxDailyHours = null;

  @JsonProperty("payRate")
  private String payRate = null;

  @JsonProperty("phones")
  private List<JavaLangObject> phones = new ArrayList<>();

  @JsonProperty("employeeId")
  private Integer employeeId = null;

  @JsonProperty("employeeNumber")
  private String employeeNumber = null;

  @JsonProperty("firstName")
  private String firstName = null;

  @JsonProperty("companyId")
  private Integer companyId = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("lastLogon")
  private String lastLogon = null;

  @JsonProperty("status")
  private String status = null;

  public ResponseEmployee maxScheduledHours(String maxScheduledHours) {
    this.maxScheduledHours = maxScheduledHours;
    return this;
  }

   /**
   * Get maxScheduledHours
   * @return maxScheduledHours
  **/
  public String getMaxScheduledHours() {
    return maxScheduledHours;
  }

  public void setMaxScheduledHours(String maxScheduledHours) {
    this.maxScheduledHours = maxScheduledHours;
  }

  public ResponseEmployee lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public ResponseEmployee hireDate(String hireDate) {
    this.hireDate = hireDate;
    return this;
  }

   /**
   * Get hireDate
   * @return hireDate
  **/
  public String getHireDate() {
    return hireDate;
  }

  public void setHireDate(String hireDate) {
    this.hireDate = hireDate;
  }

  public ResponseEmployee logonCount(String logonCount) {
    this.logonCount = logonCount;
    return this;
  }

   /**
   * Get logonCount
   * @return logonCount
  **/
  public String getLogonCount() {
    return logonCount;
  }

  public void setLogonCount(String logonCount) {
    this.logonCount = logonCount;
  }

  public ResponseEmployee maxDailyHours(String maxDailyHours) {
    this.maxDailyHours = maxDailyHours;
    return this;
  }

   /**
   * Get maxDailyHours
   * @return maxDailyHours
  **/
  public String getMaxDailyHours() {
    return maxDailyHours;
  }

  public void setMaxDailyHours(String maxDailyHours) {
    this.maxDailyHours = maxDailyHours;
  }

  public ResponseEmployee payRate(String payRate) {
    this.payRate = payRate;
    return this;
  }

   /**
   * Get payRate
   * @return payRate
  **/
  public String getPayRate() {
    return payRate;
  }

  public void setPayRate(String payRate) {
    this.payRate = payRate;
  }

  public ResponseEmployee phones(List<JavaLangObject> phones) {
    this.phones = phones;
    return this;
  }

  public ResponseEmployee addPhonesItem(JavaLangObject phonesItem) {
    this.phones.add(phonesItem);
    return this;
  }

   /**
   * Get phones
   * @return phones
  **/
  public List<JavaLangObject> getPhones() {
    return phones;
  }

  public void setPhones(List<JavaLangObject> phones) {
    this.phones = phones;
  }

  public ResponseEmployee employeeId(Integer employeeId) {
    this.employeeId = employeeId;
    return this;
  }

   /**
   * Get employeeId
   * @return employeeId
  **/
  public Integer getEmployeeId() {
    return employeeId;
  }

  public void setEmployeeId(Integer employeeId) {
    this.employeeId = employeeId;
  }

  public ResponseEmployee employeeNumber(String employeeNumber) {
    this.employeeNumber = employeeNumber;
    return this;
  }

   /**
   * Get employeeNumber
   * @return employeeNumber
  **/
  public String getEmployeeNumber() {
    return employeeNumber;
  }

  public void setEmployeeNumber(String employeeNumber) {
    this.employeeNumber = employeeNumber;
  }

  public ResponseEmployee firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public ResponseEmployee companyId(Integer companyId) {
    this.companyId = companyId;
    return this;
  }

   /**
   * Get companyId
   * @return companyId
  **/
  public Integer getCompanyId() {
    return companyId;
  }

  public void setCompanyId(Integer companyId) {
    this.companyId = companyId;
  }

  public ResponseEmployee email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public ResponseEmployee lastLogon(String lastLogon) {
    this.lastLogon = lastLogon;
    return this;
  }

   /**
   * Get lastLogon
   * @return lastLogon
  **/
  public String getLastLogon() {
    return lastLogon;
  }

  public void setLastLogon(String lastLogon) {
    this.lastLogon = lastLogon;
  }

  public ResponseEmployee status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseEmployee Response_employee = (ResponseEmployee) o;
    return Objects.equals(this.maxScheduledHours, Response_employee.maxScheduledHours) &&
        Objects.equals(this.lastName, Response_employee.lastName) &&
        Objects.equals(this.hireDate, Response_employee.hireDate) &&
        Objects.equals(this.logonCount, Response_employee.logonCount) &&
        Objects.equals(this.maxDailyHours, Response_employee.maxDailyHours) &&
        Objects.equals(this.payRate, Response_employee.payRate) &&
        Objects.equals(this.phones, Response_employee.phones) &&
        Objects.equals(this.employeeId, Response_employee.employeeId) &&
        Objects.equals(this.employeeNumber, Response_employee.employeeNumber) &&
        Objects.equals(this.firstName, Response_employee.firstName) &&
        Objects.equals(this.companyId, Response_employee.companyId) &&
        Objects.equals(this.email, Response_employee.email) &&
        Objects.equals(this.lastLogon, Response_employee.lastLogon) &&
        Objects.equals(this.status, Response_employee.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxScheduledHours, lastName, hireDate, logonCount, maxDailyHours, payRate, phones, employeeId, employeeNumber, firstName, companyId, email, lastLogon, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseEmployee {\n");
    
    sb.append("    maxScheduledHours: ").append(toIndentedString(maxScheduledHours)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    hireDate: ").append(toIndentedString(hireDate)).append("\n");
    sb.append("    logonCount: ").append(toIndentedString(logonCount)).append("\n");
    sb.append("    maxDailyHours: ").append(toIndentedString(maxDailyHours)).append("\n");
    sb.append("    payRate: ").append(toIndentedString(payRate)).append("\n");
    sb.append("    phones: ").append(toIndentedString(phones)).append("\n");
    sb.append("    employeeId: ").append(toIndentedString(employeeId)).append("\n");
    sb.append("    employeeNumber: ").append(toIndentedString(employeeNumber)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    lastLogon: ").append(toIndentedString(lastLogon)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
