/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.when_to_work.timeOffRequests.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.when_to_work.timeOffRequests.model.ResponseTimeOffRequestsEntryItem;
import java.util.ArrayList;
import java.util.List;
/**
 * RootResponse
 */

public class RootResponse {
  @JsonProperty("timeOffRequests")
  private List<ResponseTimeOffRequestsEntryItem> timeOffRequests = new ArrayList<>();

  public RootResponse timeOffRequests(List<ResponseTimeOffRequestsEntryItem> timeOffRequests) {
    this.timeOffRequests = timeOffRequests;
    return this;
  }

  public RootResponse addTimeOffRequestsItem(ResponseTimeOffRequestsEntryItem timeOffRequestsItem) {
    this.timeOffRequests.add(timeOffRequestsItem);
    return this;
  }

   /**
   * Get timeOffRequests
   * @return timeOffRequests
  **/
  public List<ResponseTimeOffRequestsEntryItem> getTimeOffRequests() {
    return timeOffRequests;
  }

  public void setTimeOffRequests(List<ResponseTimeOffRequestsEntryItem> timeOffRequests) {
    this.timeOffRequests = timeOffRequests;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootResponse RootResponse = (RootResponse) o;
    return Objects.equals(this.timeOffRequests, RootResponse.timeOffRequests);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeOffRequests);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootResponse {\n");
    
    sb.append("    timeOffRequests: ").append(toIndentedString(timeOffRequests)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
