/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.when_to_work.PostWeekPref.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * RootRequest
 */

public class RootRequest {
  @JsonProperty("companyId")
  private Integer companyId = null;

  @JsonProperty("editedBy")
  private Integer editedBy = null;

  @JsonProperty("employeeId")
  private Integer employeeId = null;

  @JsonProperty("compression")
  private Integer compression = null;

  @JsonProperty("startDate")
  private String startDate = null;

  @JsonProperty("prefs")
  private String prefs = null;

  public RootRequest companyId(Integer companyId) {
    this.companyId = companyId;
    return this;
  }

   /**
   * Get companyId
   * @return companyId
  **/
  public Integer getCompanyId() {
    return companyId;
  }

  public void setCompanyId(Integer companyId) {
    this.companyId = companyId;
  }

  public RootRequest editedBy(Integer editedBy) {
    this.editedBy = editedBy;
    return this;
  }

   /**
   * Get editedBy
   * @return editedBy
  **/
  public Integer getEditedBy() {
    return editedBy;
  }

  public void setEditedBy(Integer editedBy) {
    this.editedBy = editedBy;
  }

  public RootRequest employeeId(Integer employeeId) {
    this.employeeId = employeeId;
    return this;
  }

   /**
   * Get employeeId
   * @return employeeId
  **/
  public Integer getEmployeeId() {
    return employeeId;
  }

  public void setEmployeeId(Integer employeeId) {
    this.employeeId = employeeId;
  }

  public RootRequest compression(Integer compression) {
    this.compression = compression;
    return this;
  }

   /**
   * Get compression
   * @return compression
  **/
  public Integer getCompression() {
    return compression;
  }

  public void setCompression(Integer compression) {
    this.compression = compression;
  }

  public RootRequest startDate(String startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  public String getStartDate() {
    return startDate;
  }

  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }

  public RootRequest prefs(String prefs) {
    this.prefs = prefs;
    return this;
  }

   /**
   * Get prefs
   * @return prefs
  **/
  public String getPrefs() {
    return prefs;
  }

  public void setPrefs(String prefs) {
    this.prefs = prefs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootRequest RootRequest = (RootRequest) o;
    return Objects.equals(this.companyId, RootRequest.companyId) &&
        Objects.equals(this.editedBy, RootRequest.editedBy) &&
        Objects.equals(this.employeeId, RootRequest.employeeId) &&
        Objects.equals(this.compression, RootRequest.compression) &&
        Objects.equals(this.startDate, RootRequest.startDate) &&
        Objects.equals(this.prefs, RootRequest.prefs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyId, editedBy, employeeId, compression, startDate, prefs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootRequest {\n");
    
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    editedBy: ").append(toIndentedString(editedBy)).append("\n");
    sb.append("    employeeId: ").append(toIndentedString(employeeId)).append("\n");
    sb.append("    compression: ").append(toIndentedString(compression)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    prefs: ").append(toIndentedString(prefs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
