/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.when_to_work.precheck.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.when_to_work.precheck.model.JavaLangObject;
import java.util.ArrayList;
import java.util.List;
/**
 * RootResponse
 */

public class RootResponse {
  @JsonProperty("conflicts")
  private List<JavaLangObject> conflicts = new ArrayList<>();

  @JsonProperty("hasConflicts")
  private Boolean hasConflicts = null;

  public RootResponse conflicts(List<JavaLangObject> conflicts) {
    this.conflicts = conflicts;
    return this;
  }

  public RootResponse addConflictsItem(JavaLangObject conflictsItem) {
    this.conflicts.add(conflictsItem);
    return this;
  }

   /**
   * Get conflicts
   * @return conflicts
  **/
  public List<JavaLangObject> getConflicts() {
    return conflicts;
  }

  public void setConflicts(List<JavaLangObject> conflicts) {
    this.conflicts = conflicts;
  }

  public RootResponse hasConflicts(Boolean hasConflicts) {
    this.hasConflicts = hasConflicts;
    return this;
  }

   /**
   * Get hasConflicts
   * @return hasConflicts
  **/
  public Boolean isHasConflicts() {
    return hasConflicts;
  }

  public void setHasConflicts(Boolean hasConflicts) {
    this.hasConflicts = hasConflicts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootResponse RootResponse = (RootResponse) o;
    return Objects.equals(this.conflicts, RootResponse.conflicts) &&
        Objects.equals(this.hasConflicts, RootResponse.hasConflicts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conflicts, hasConflicts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootResponse {\n");
    
    sb.append("    conflicts: ").append(toIndentedString(conflicts)).append("\n");
    sb.append("    hasConflicts: ").append(toIndentedString(hasConflicts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
