/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Lazy;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.commons.WMObjectMapper;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.annotations.EntityService;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.when_to_work.when2work.Category;
import com.wavemaker.when_to_work.when2work.GroupCat;
import com.wavemaker.when_to_work.when2work.ScheduledEmployee;


/**
 * ServiceImpl object for domain model class Category.
 *
 * @see Category
 */
@Service("when2work.CategoryService")
@Validated
@EntityService(entityClass = Category.class, serviceId = "when2work")
public class CategoryServiceImpl implements CategoryService {

    private static final Logger LOGGER = LoggerFactory.getLogger(CategoryServiceImpl.class);

    @Lazy
    @Autowired
    @Qualifier("when2work.GroupCatService")
    private GroupCatService groupCatService;

    @Lazy
    @Autowired
    @Qualifier("when2work.ScheduledEmployeeService")
    private ScheduledEmployeeService scheduledEmployeeService;

    @Autowired
    @Qualifier("when2work.CategoryDao")
    private WMGenericDao<Category, Integer> wmGenericDao;


    public void setWMGenericDao(WMGenericDao<Category, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public Category create(Category category) {
        LOGGER.debug("Creating a new Category with information: {}", category);

        Category categoryCreated = this.wmGenericDao.create(category);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(categoryCreated);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Category getById(Integer categoryIdInstance) {
        LOGGER.debug("Finding Category by id: {}", categoryIdInstance);
        return this.wmGenericDao.findById(categoryIdInstance);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Category findById(Integer categoryIdInstance) {
        LOGGER.debug("Finding Category by id: {}", categoryIdInstance);
        try {
            return this.wmGenericDao.findById(categoryIdInstance);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No Category found with id: {}", categoryIdInstance, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public List<Category> findByMultipleIds(List<Integer> categoryIdInstances, boolean orderedReturn) {
        LOGGER.debug("Finding Categories by ids: {}", categoryIdInstances);

        return this.wmGenericDao.findByMultipleIds(categoryIdInstances, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "when2workTransactionManager")
    @Override
    public Category update(Category category) {
        LOGGER.debug("Updating Category with information: {}", category);

        this.wmGenericDao.update(category);
        this.wmGenericDao.refresh(category);

        return category;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public Category partialUpdate(Integer categoryIdInstance, Map<String, Object>categoryPatch) {
        LOGGER.debug("Partially Updating the Category with id: {}", categoryIdInstance);

        Category category = getById(categoryIdInstance);

        try {
            ObjectReader categoryReader = WMObjectMapper.getInstance().reader().forType(Category.class).withValueToUpdate(category);
            category = categoryReader.readValue(WMObjectMapper.getInstance().writeValueAsString(categoryPatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", categoryPatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        category = update(category);

        return category;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public Category delete(Integer categoryIdInstance) {
        LOGGER.debug("Deleting Category with id: {}", categoryIdInstance);
        Category deleted = this.wmGenericDao.findById(categoryIdInstance);
        if (deleted == null) {
            LOGGER.debug("No Category found with id: {}", categoryIdInstance);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), Category.class.getSimpleName(), categoryIdInstance);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public void delete(Category category) {
        LOGGER.debug("Deleting Category with {}", category);
        this.wmGenericDao.delete(category);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<Category> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Categories");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<Category> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Categories");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service when2work for table Category to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service when2work for table Category to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<GroupCat> findAssociatedGroupCats(Integer categoryId, Pageable pageable) {
        LOGGER.debug("Fetching all associated groupCats");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("category.categoryId = '" + categoryId + "'");

        return groupCatService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<ScheduledEmployee> findAssociatedScheduledEmployees(Integer categoryId, Pageable pageable) {
        LOGGER.debug("Fetching all associated scheduledEmployees");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("category.categoryId = '" + categoryId + "'");

        return scheduledEmployeeService.findAll(queryBuilder.toString(), pageable);
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service GroupCatService instance
     */
    protected void setGroupCatService(GroupCatService service) {
        this.groupCatService = service;
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service ScheduledEmployeeService instance
     */
    protected void setScheduledEmployeeService(ScheduledEmployeeService service) {
        this.scheduledEmployeeService = service;
    }

}
