/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Lazy;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.commons.WMObjectMapper;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.annotations.EntityService;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.when_to_work.when2work.CatGroup;
import com.wavemaker.when_to_work.when2work.GroupCat;


/**
 * ServiceImpl object for domain model class CatGroup.
 *
 * @see CatGroup
 */
@Service("when2work.CatGroupService")
@Validated
@EntityService(entityClass = CatGroup.class, serviceId = "when2work")
public class CatGroupServiceImpl implements CatGroupService {

    private static final Logger LOGGER = LoggerFactory.getLogger(CatGroupServiceImpl.class);

    @Lazy
    @Autowired
    @Qualifier("when2work.GroupCatService")
    private GroupCatService groupCatService;

    @Autowired
    @Qualifier("when2work.CatGroupDao")
    private WMGenericDao<CatGroup, Integer> wmGenericDao;


    public void setWMGenericDao(WMGenericDao<CatGroup, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public CatGroup create(CatGroup catGroup) {
        LOGGER.debug("Creating a new CatGroup with information: {}", catGroup);

        CatGroup catGroupCreated = this.wmGenericDao.create(catGroup);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(catGroupCreated);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public CatGroup getById(Integer catgroupId) {
        LOGGER.debug("Finding CatGroup by id: {}", catgroupId);
        return this.wmGenericDao.findById(catgroupId);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public CatGroup findById(Integer catgroupId) {
        LOGGER.debug("Finding CatGroup by id: {}", catgroupId);
        try {
            return this.wmGenericDao.findById(catgroupId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No CatGroup found with id: {}", catgroupId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public List<CatGroup> findByMultipleIds(List<Integer> catgroupIds, boolean orderedReturn) {
        LOGGER.debug("Finding CatGroups by ids: {}", catgroupIds);

        return this.wmGenericDao.findByMultipleIds(catgroupIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "when2workTransactionManager")
    @Override
    public CatGroup update(CatGroup catGroup) {
        LOGGER.debug("Updating CatGroup with information: {}", catGroup);

        this.wmGenericDao.update(catGroup);
        this.wmGenericDao.refresh(catGroup);

        return catGroup;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public CatGroup partialUpdate(Integer catgroupId, Map<String, Object>catGroupPatch) {
        LOGGER.debug("Partially Updating the CatGroup with id: {}", catgroupId);

        CatGroup catGroup = getById(catgroupId);

        try {
            ObjectReader catGroupReader = WMObjectMapper.getInstance().reader().forType(CatGroup.class).withValueToUpdate(catGroup);
            catGroup = catGroupReader.readValue(WMObjectMapper.getInstance().writeValueAsString(catGroupPatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", catGroupPatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        catGroup = update(catGroup);

        return catGroup;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public CatGroup delete(Integer catgroupId) {
        LOGGER.debug("Deleting CatGroup with id: {}", catgroupId);
        CatGroup deleted = this.wmGenericDao.findById(catgroupId);
        if (deleted == null) {
            LOGGER.debug("No CatGroup found with id: {}", catgroupId);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), CatGroup.class.getSimpleName(), catgroupId);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public void delete(CatGroup catGroup) {
        LOGGER.debug("Deleting CatGroup with {}", catGroup);
        this.wmGenericDao.delete(catGroup);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<CatGroup> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all CatGroups");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<CatGroup> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all CatGroups");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service when2work for table CatGroup to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service when2work for table CatGroup to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<GroupCat> findAssociatedGroupCats(Integer groupId, Pageable pageable) {
        LOGGER.debug("Fetching all associated groupCats");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("catGroup.groupId = '" + groupId + "'");

        return groupCatService.findAll(queryBuilder.toString(), pageable);
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service GroupCatService instance
     */
    protected void setGroupCatService(GroupCatService service) {
        this.groupCatService = service;
    }

}
