/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.commons.WMObjectMapper;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.annotations.EntityService;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.when_to_work.when2work.EmployeeSkill;
import com.wavemaker.when_to_work.when2work.EmployeeSkillId;


/**
 * ServiceImpl object for domain model class EmployeeSkill.
 *
 * @see EmployeeSkill
 */
@Service("when2work.EmployeeSkillService")
@Validated
@EntityService(entityClass = EmployeeSkill.class, serviceId = "when2work")
public class EmployeeSkillServiceImpl implements EmployeeSkillService {

    private static final Logger LOGGER = LoggerFactory.getLogger(EmployeeSkillServiceImpl.class);


    @Autowired
    @Qualifier("when2work.EmployeeSkillDao")
    private WMGenericDao<EmployeeSkill, EmployeeSkillId> wmGenericDao;


    public void setWMGenericDao(WMGenericDao<EmployeeSkill, EmployeeSkillId> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public EmployeeSkill create(EmployeeSkill employeeSkill) {
        LOGGER.debug("Creating a new EmployeeSkill with information: {}", employeeSkill);

        EmployeeSkill employeeSkillCreated = this.wmGenericDao.create(employeeSkill);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(employeeSkillCreated);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public EmployeeSkill getById(EmployeeSkillId employeeskillId) {
        LOGGER.debug("Finding EmployeeSkill by id: {}", employeeskillId);
        return this.wmGenericDao.findById(employeeskillId);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public EmployeeSkill findById(EmployeeSkillId employeeskillId) {
        LOGGER.debug("Finding EmployeeSkill by id: {}", employeeskillId);
        try {
            return this.wmGenericDao.findById(employeeskillId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No EmployeeSkill found with id: {}", employeeskillId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public List<EmployeeSkill> findByMultipleIds(List<EmployeeSkillId> employeeskillIds, boolean orderedReturn) {
        LOGGER.debug("Finding EmployeeSkills by ids: {}", employeeskillIds);

        return this.wmGenericDao.findByMultipleIds(employeeskillIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "when2workTransactionManager")
    @Override
    public EmployeeSkill update(EmployeeSkill employeeSkill) {
        LOGGER.debug("Updating EmployeeSkill with information: {}", employeeSkill);

        this.wmGenericDao.update(employeeSkill);
        this.wmGenericDao.refresh(employeeSkill);

        return employeeSkill;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public EmployeeSkill partialUpdate(EmployeeSkillId employeeskillId, Map<String, Object>employeeSkillPatch) {
        LOGGER.debug("Partially Updating the EmployeeSkill with id: {}", employeeskillId);

        EmployeeSkill employeeSkill = getById(employeeskillId);

        try {
            ObjectReader employeeSkillReader = WMObjectMapper.getInstance().reader().forType(EmployeeSkill.class).withValueToUpdate(employeeSkill);
            employeeSkill = employeeSkillReader.readValue(WMObjectMapper.getInstance().writeValueAsString(employeeSkillPatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", employeeSkillPatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        employeeSkill = update(employeeSkill);

        return employeeSkill;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public EmployeeSkill delete(EmployeeSkillId employeeskillId) {
        LOGGER.debug("Deleting EmployeeSkill with id: {}", employeeskillId);
        EmployeeSkill deleted = this.wmGenericDao.findById(employeeskillId);
        if (deleted == null) {
            LOGGER.debug("No EmployeeSkill found with id: {}", employeeskillId);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), EmployeeSkill.class.getSimpleName(), employeeskillId);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public void delete(EmployeeSkill employeeSkill) {
        LOGGER.debug("Deleting EmployeeSkill with {}", employeeSkill);
        this.wmGenericDao.delete(employeeSkill);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<EmployeeSkill> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all EmployeeSkills");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<EmployeeSkill> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all EmployeeSkills");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service when2work for table EmployeeSkill to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service when2work for table EmployeeSkill to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}
