/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import jakarta.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.when_to_work.when2work.FlywaySchemaHistory;

/**
 * Service object for domain model class {@link FlywaySchemaHistory}.
 */
public interface FlywaySchemaHistoryService {

    /**
     * Creates a new FlywaySchemaHistory. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on FlywaySchemaHistory if any.
     *
     * @param flywaySchemaHistory Details of the FlywaySchemaHistory to be created; value cannot be null.
     * @return The newly created FlywaySchemaHistory.
     */
    FlywaySchemaHistory create(@Valid FlywaySchemaHistory flywaySchemaHistory);


	/**
     * Returns FlywaySchemaHistory by given id if exists.
     *
     * @param flywayschemahistoryId The id of the FlywaySchemaHistory to get; value cannot be null.
     * @return FlywaySchemaHistory associated with the given flywayschemahistoryId.
	 * @throws EntityNotFoundException If no FlywaySchemaHistory is found.
     */
    FlywaySchemaHistory getById(Integer flywayschemahistoryId);

    /**
     * Find and return the FlywaySchemaHistory by given id if exists, returns null otherwise.
     *
     * @param flywayschemahistoryId The id of the FlywaySchemaHistory to get; value cannot be null.
     * @return FlywaySchemaHistory associated with the given flywayschemahistoryId.
     */
    FlywaySchemaHistory findById(Integer flywayschemahistoryId);

	/**
     * Find and return the list of FlywaySchemaHistories by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param flywayschemahistoryIds The id's of the FlywaySchemaHistory to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return FlywaySchemaHistories associated with the given flywayschemahistoryIds.
     */
    List<FlywaySchemaHistory> findByMultipleIds(List<Integer> flywayschemahistoryIds, boolean orderedReturn);


    /**
     * Updates the details of an existing FlywaySchemaHistory. It replaces all fields of the existing FlywaySchemaHistory with the given flywaySchemaHistory.
     *
     * This method overrides the input field values using Server side or database managed properties defined on FlywaySchemaHistory if any.
     *
     * @param flywaySchemaHistory The details of the FlywaySchemaHistory to be updated; value cannot be null.
     * @return The updated FlywaySchemaHistory.
     * @throws EntityNotFoundException if no FlywaySchemaHistory is found with given input.
     */
    FlywaySchemaHistory update(@Valid FlywaySchemaHistory flywaySchemaHistory);


    /**
     * Partially updates the details of an existing FlywaySchemaHistory. It updates only the
     * fields of the existing FlywaySchemaHistory which are passed in the flywaySchemaHistoryPatch.
     *
     * This method overrides the input field values using Server side or database managed properties defined on FlywaySchemaHistory if any.
     *
     * @param flywayschemahistoryId The id of the FlywaySchemaHistory to be deleted; value cannot be null.
     * @param flywaySchemaHistoryPatch The partial data of FlywaySchemaHistory which is supposed to be updated; value cannot be null.
     * @return The updated FlywaySchemaHistory.
     * @throws EntityNotFoundException if no FlywaySchemaHistory is found with given input.
     */
    FlywaySchemaHistory partialUpdate(Integer flywayschemahistoryId, Map<String, Object> flywaySchemaHistoryPatch);

    /**
     * Deletes an existing FlywaySchemaHistory with the given id.
     *
     * @param flywayschemahistoryId The id of the FlywaySchemaHistory to be deleted; value cannot be null.
     * @return The deleted FlywaySchemaHistory.
     * @throws EntityNotFoundException if no FlywaySchemaHistory found with the given id.
     */
    FlywaySchemaHistory delete(Integer flywayschemahistoryId);

    /**
     * Deletes an existing FlywaySchemaHistory with the given object.
     *
     * @param flywaySchemaHistory The instance of the FlywaySchemaHistory to be deleted; value cannot be null.
     */
    void delete(FlywaySchemaHistory flywaySchemaHistory);

    /**
     * Find all FlywaySchemaHistories matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching FlywaySchemaHistories.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<FlywaySchemaHistory> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all FlywaySchemaHistories matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching FlywaySchemaHistories.
     *
     * @see Pageable
     * @see Page
     */
    Page<FlywaySchemaHistory> findAll(String query, Pageable pageable);

    /**
     * Exports all FlywaySchemaHistories matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all FlywaySchemaHistories matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the FlywaySchemaHistories in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the FlywaySchemaHistory.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}
