/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.commons.WMObjectMapper;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.annotations.EntityService;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.when_to_work.when2work.FlywaySchemaHistory;


/**
 * ServiceImpl object for domain model class FlywaySchemaHistory.
 *
 * @see FlywaySchemaHistory
 */
@Service("when2work.FlywaySchemaHistoryService")
@Validated
@EntityService(entityClass = FlywaySchemaHistory.class, serviceId = "when2work")
public class FlywaySchemaHistoryServiceImpl implements FlywaySchemaHistoryService {

    private static final Logger LOGGER = LoggerFactory.getLogger(FlywaySchemaHistoryServiceImpl.class);


    @Autowired
    @Qualifier("when2work.FlywaySchemaHistoryDao")
    private WMGenericDao<FlywaySchemaHistory, Integer> wmGenericDao;


    public void setWMGenericDao(WMGenericDao<FlywaySchemaHistory, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public FlywaySchemaHistory create(FlywaySchemaHistory flywaySchemaHistory) {
        LOGGER.debug("Creating a new FlywaySchemaHistory with information: {}", flywaySchemaHistory);

        FlywaySchemaHistory flywaySchemaHistoryCreated = this.wmGenericDao.create(flywaySchemaHistory);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(flywaySchemaHistoryCreated);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public FlywaySchemaHistory getById(Integer flywayschemahistoryId) {
        LOGGER.debug("Finding FlywaySchemaHistory by id: {}", flywayschemahistoryId);
        return this.wmGenericDao.findById(flywayschemahistoryId);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public FlywaySchemaHistory findById(Integer flywayschemahistoryId) {
        LOGGER.debug("Finding FlywaySchemaHistory by id: {}", flywayschemahistoryId);
        try {
            return this.wmGenericDao.findById(flywayschemahistoryId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No FlywaySchemaHistory found with id: {}", flywayschemahistoryId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public List<FlywaySchemaHistory> findByMultipleIds(List<Integer> flywayschemahistoryIds, boolean orderedReturn) {
        LOGGER.debug("Finding FlywaySchemaHistories by ids: {}", flywayschemahistoryIds);

        return this.wmGenericDao.findByMultipleIds(flywayschemahistoryIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "when2workTransactionManager")
    @Override
    public FlywaySchemaHistory update(FlywaySchemaHistory flywaySchemaHistory) {
        LOGGER.debug("Updating FlywaySchemaHistory with information: {}", flywaySchemaHistory);

        this.wmGenericDao.update(flywaySchemaHistory);
        this.wmGenericDao.refresh(flywaySchemaHistory);

        return flywaySchemaHistory;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public FlywaySchemaHistory partialUpdate(Integer flywayschemahistoryId, Map<String, Object>flywaySchemaHistoryPatch) {
        LOGGER.debug("Partially Updating the FlywaySchemaHistory with id: {}", flywayschemahistoryId);

        FlywaySchemaHistory flywaySchemaHistory = getById(flywayschemahistoryId);

        try {
            ObjectReader flywaySchemaHistoryReader = WMObjectMapper.getInstance().reader().forType(FlywaySchemaHistory.class).withValueToUpdate(flywaySchemaHistory);
            flywaySchemaHistory = flywaySchemaHistoryReader.readValue(WMObjectMapper.getInstance().writeValueAsString(flywaySchemaHistoryPatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", flywaySchemaHistoryPatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        flywaySchemaHistory = update(flywaySchemaHistory);

        return flywaySchemaHistory;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public FlywaySchemaHistory delete(Integer flywayschemahistoryId) {
        LOGGER.debug("Deleting FlywaySchemaHistory with id: {}", flywayschemahistoryId);
        FlywaySchemaHistory deleted = this.wmGenericDao.findById(flywayschemahistoryId);
        if (deleted == null) {
            LOGGER.debug("No FlywaySchemaHistory found with id: {}", flywayschemahistoryId);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), FlywaySchemaHistory.class.getSimpleName(), flywayschemahistoryId);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public void delete(FlywaySchemaHistory flywaySchemaHistory) {
        LOGGER.debug("Deleting FlywaySchemaHistory with {}", flywaySchemaHistory);
        this.wmGenericDao.delete(flywaySchemaHistory);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<FlywaySchemaHistory> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all FlywaySchemaHistories");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<FlywaySchemaHistory> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all FlywaySchemaHistories");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service when2work for table FlywaySchemaHistory to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service when2work for table FlywaySchemaHistory to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}
