/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.commons.WMObjectMapper;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.annotations.EntityService;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.when_to_work.when2work.GroupSkill;
import com.wavemaker.when_to_work.when2work.GroupSkillId;


/**
 * ServiceImpl object for domain model class GroupSkill.
 *
 * @see GroupSkill
 */
@Service("when2work.GroupSkillService")
@Validated
@EntityService(entityClass = GroupSkill.class, serviceId = "when2work")
public class GroupSkillServiceImpl implements GroupSkillService {

    private static final Logger LOGGER = LoggerFactory.getLogger(GroupSkillServiceImpl.class);


    @Autowired
    @Qualifier("when2work.GroupSkillDao")
    private WMGenericDao<GroupSkill, GroupSkillId> wmGenericDao;


    public void setWMGenericDao(WMGenericDao<GroupSkill, GroupSkillId> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public GroupSkill create(GroupSkill groupSkill) {
        LOGGER.debug("Creating a new GroupSkill with information: {}", groupSkill);

        GroupSkill groupSkillCreated = this.wmGenericDao.create(groupSkill);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(groupSkillCreated);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public GroupSkill getById(GroupSkillId groupskillId) {
        LOGGER.debug("Finding GroupSkill by id: {}", groupskillId);
        return this.wmGenericDao.findById(groupskillId);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public GroupSkill findById(GroupSkillId groupskillId) {
        LOGGER.debug("Finding GroupSkill by id: {}", groupskillId);
        try {
            return this.wmGenericDao.findById(groupskillId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No GroupSkill found with id: {}", groupskillId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public List<GroupSkill> findByMultipleIds(List<GroupSkillId> groupskillIds, boolean orderedReturn) {
        LOGGER.debug("Finding GroupSkills by ids: {}", groupskillIds);

        return this.wmGenericDao.findByMultipleIds(groupskillIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "when2workTransactionManager")
    @Override
    public GroupSkill update(GroupSkill groupSkill) {
        LOGGER.debug("Updating GroupSkill with information: {}", groupSkill);

        this.wmGenericDao.update(groupSkill);
        this.wmGenericDao.refresh(groupSkill);

        return groupSkill;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public GroupSkill partialUpdate(GroupSkillId groupskillId, Map<String, Object>groupSkillPatch) {
        LOGGER.debug("Partially Updating the GroupSkill with id: {}", groupskillId);

        GroupSkill groupSkill = getById(groupskillId);

        try {
            ObjectReader groupSkillReader = WMObjectMapper.getInstance().reader().forType(GroupSkill.class).withValueToUpdate(groupSkill);
            groupSkill = groupSkillReader.readValue(WMObjectMapper.getInstance().writeValueAsString(groupSkillPatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", groupSkillPatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        groupSkill = update(groupSkill);

        return groupSkill;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public GroupSkill delete(GroupSkillId groupskillId) {
        LOGGER.debug("Deleting GroupSkill with id: {}", groupskillId);
        GroupSkill deleted = this.wmGenericDao.findById(groupskillId);
        if (deleted == null) {
            LOGGER.debug("No GroupSkill found with id: {}", groupskillId);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), GroupSkill.class.getSimpleName(), groupskillId);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public void delete(GroupSkill groupSkill) {
        LOGGER.debug("Deleting GroupSkill with {}", groupSkill);
        this.wmGenericDao.delete(groupSkill);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<GroupSkill> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all GroupSkills");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<GroupSkill> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all GroupSkills");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service when2work for table GroupSkill to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service when2work for table GroupSkill to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}
