/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import jakarta.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.when_to_work.when2work.GroupCat;
import com.wavemaker.when_to_work.when2work.GroupCatId;

/**
 * Service object for domain model class {@link GroupCat}.
 */
public interface GroupCatService {

    /**
     * Creates a new GroupCat. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on GroupCat if any.
     *
     * @param groupCat Details of the GroupCat to be created; value cannot be null.
     * @return The newly created GroupCat.
     */
    GroupCat create(@Valid GroupCat groupCat);


	/**
     * Returns GroupCat by given id if exists.
     *
     * @param groupcatId The id of the GroupCat to get; value cannot be null.
     * @return GroupCat associated with the given groupcatId.
	 * @throws EntityNotFoundException If no GroupCat is found.
     */
    GroupCat getById(GroupCatId groupcatId);

    /**
     * Find and return the GroupCat by given id if exists, returns null otherwise.
     *
     * @param groupcatId The id of the GroupCat to get; value cannot be null.
     * @return GroupCat associated with the given groupcatId.
     */
    GroupCat findById(GroupCatId groupcatId);

	/**
     * Find and return the list of GroupCats by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param groupcatIds The id's of the GroupCat to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return GroupCats associated with the given groupcatIds.
     */
    List<GroupCat> findByMultipleIds(List<GroupCatId> groupcatIds, boolean orderedReturn);


    /**
     * Updates the details of an existing GroupCat. It replaces all fields of the existing GroupCat with the given groupCat.
     *
     * This method overrides the input field values using Server side or database managed properties defined on GroupCat if any.
     *
     * @param groupCat The details of the GroupCat to be updated; value cannot be null.
     * @return The updated GroupCat.
     * @throws EntityNotFoundException if no GroupCat is found with given input.
     */
    GroupCat update(@Valid GroupCat groupCat);


    /**
     * Partially updates the details of an existing GroupCat. It updates only the
     * fields of the existing GroupCat which are passed in the groupCatPatch.
     *
     * This method overrides the input field values using Server side or database managed properties defined on GroupCat if any.
     *
     * @param groupcatId The id of the GroupCat to be deleted; value cannot be null.
     * @param groupCatPatch The partial data of GroupCat which is supposed to be updated; value cannot be null.
     * @return The updated GroupCat.
     * @throws EntityNotFoundException if no GroupCat is found with given input.
     */
    GroupCat partialUpdate(GroupCatId groupcatId, Map<String, Object> groupCatPatch);

    /**
     * Deletes an existing GroupCat with the given id.
     *
     * @param groupcatId The id of the GroupCat to be deleted; value cannot be null.
     * @return The deleted GroupCat.
     * @throws EntityNotFoundException if no GroupCat found with the given id.
     */
    GroupCat delete(GroupCatId groupcatId);

    /**
     * Deletes an existing GroupCat with the given object.
     *
     * @param groupCat The instance of the GroupCat to be deleted; value cannot be null.
     */
    void delete(GroupCat groupCat);

    /**
     * Find all GroupCats matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching GroupCats.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<GroupCat> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all GroupCats matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching GroupCats.
     *
     * @see Pageable
     * @see Page
     */
    Page<GroupCat> findAll(String query, Pageable pageable);

    /**
     * Exports all GroupCats matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all GroupCats matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the GroupCats in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the GroupCat.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}
