/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Lazy;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.commons.WMObjectMapper;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.annotations.EntityService;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.when_to_work.when2work.Schedule;
import com.wavemaker.when_to_work.when2work.ScheduledEmployee;


/**
 * ServiceImpl object for domain model class Schedule.
 *
 * @see Schedule
 */
@Service("when2work.ScheduleService")
@Validated
@EntityService(entityClass = Schedule.class, serviceId = "when2work")
public class ScheduleServiceImpl implements ScheduleService {

    private static final Logger LOGGER = LoggerFactory.getLogger(ScheduleServiceImpl.class);

    @Lazy
    @Autowired
    @Qualifier("when2work.ScheduledEmployeeService")
    private ScheduledEmployeeService scheduledEmployeeService;

    @Autowired
    @Qualifier("when2work.ScheduleDao")
    private WMGenericDao<Schedule, Integer> wmGenericDao;


    public void setWMGenericDao(WMGenericDao<Schedule, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public Schedule create(Schedule schedule) {
        LOGGER.debug("Creating a new Schedule with information: {}", schedule);

        Schedule scheduleCreated = this.wmGenericDao.create(schedule);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(scheduleCreated);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Schedule getById(Integer scheduleIdInstance) {
        LOGGER.debug("Finding Schedule by id: {}", scheduleIdInstance);
        return this.wmGenericDao.findById(scheduleIdInstance);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Schedule findById(Integer scheduleIdInstance) {
        LOGGER.debug("Finding Schedule by id: {}", scheduleIdInstance);
        try {
            return this.wmGenericDao.findById(scheduleIdInstance);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No Schedule found with id: {}", scheduleIdInstance, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public List<Schedule> findByMultipleIds(List<Integer> scheduleIdInstances, boolean orderedReturn) {
        LOGGER.debug("Finding Schedules by ids: {}", scheduleIdInstances);

        return this.wmGenericDao.findByMultipleIds(scheduleIdInstances, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "when2workTransactionManager")
    @Override
    public Schedule update(Schedule schedule) {
        LOGGER.debug("Updating Schedule with information: {}", schedule);

        this.wmGenericDao.update(schedule);
        this.wmGenericDao.refresh(schedule);

        return schedule;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public Schedule partialUpdate(Integer scheduleIdInstance, Map<String, Object>schedulePatch) {
        LOGGER.debug("Partially Updating the Schedule with id: {}", scheduleIdInstance);

        Schedule schedule = getById(scheduleIdInstance);

        try {
            ObjectReader scheduleReader = WMObjectMapper.getInstance().reader().forType(Schedule.class).withValueToUpdate(schedule);
            schedule = scheduleReader.readValue(WMObjectMapper.getInstance().writeValueAsString(schedulePatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", schedulePatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        schedule = update(schedule);

        return schedule;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public Schedule delete(Integer scheduleIdInstance) {
        LOGGER.debug("Deleting Schedule with id: {}", scheduleIdInstance);
        Schedule deleted = this.wmGenericDao.findById(scheduleIdInstance);
        if (deleted == null) {
            LOGGER.debug("No Schedule found with id: {}", scheduleIdInstance);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), Schedule.class.getSimpleName(), scheduleIdInstance);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public void delete(Schedule schedule) {
        LOGGER.debug("Deleting Schedule with {}", schedule);
        this.wmGenericDao.delete(schedule);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<Schedule> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Schedules");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<Schedule> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Schedules");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service when2work for table Schedule to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service when2work for table Schedule to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<ScheduledEmployee> findAssociatedScheduledEmployees(Integer scheduleId, Pageable pageable) {
        LOGGER.debug("Fetching all associated scheduledEmployees");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("schedule.scheduleId = '" + scheduleId + "'");

        return scheduledEmployeeService.findAll(queryBuilder.toString(), pageable);
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service ScheduledEmployeeService instance
     */
    protected void setScheduledEmployeeService(ScheduledEmployeeService service) {
        this.scheduledEmployeeService = service;
    }

}
