/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.commons.WMObjectMapper;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.annotations.EntityService;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.when_to_work.when2work.ScheduledEmployee;


/**
 * ServiceImpl object for domain model class ScheduledEmployee.
 *
 * @see ScheduledEmployee
 */
@Service("when2work.ScheduledEmployeeService")
@Validated
@EntityService(entityClass = ScheduledEmployee.class, serviceId = "when2work")
public class ScheduledEmployeeServiceImpl implements ScheduledEmployeeService {

    private static final Logger LOGGER = LoggerFactory.getLogger(ScheduledEmployeeServiceImpl.class);


    @Autowired
    @Qualifier("when2work.ScheduledEmployeeDao")
    private WMGenericDao<ScheduledEmployee, Integer> wmGenericDao;


    public void setWMGenericDao(WMGenericDao<ScheduledEmployee, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public ScheduledEmployee create(ScheduledEmployee scheduledEmployee) {
        LOGGER.debug("Creating a new ScheduledEmployee with information: {}", scheduledEmployee);

        ScheduledEmployee scheduledEmployeeCreated = this.wmGenericDao.create(scheduledEmployee);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(scheduledEmployeeCreated);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public ScheduledEmployee getById(Integer scheduledemployeeId) {
        LOGGER.debug("Finding ScheduledEmployee by id: {}", scheduledemployeeId);
        return this.wmGenericDao.findById(scheduledemployeeId);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public ScheduledEmployee findById(Integer scheduledemployeeId) {
        LOGGER.debug("Finding ScheduledEmployee by id: {}", scheduledemployeeId);
        try {
            return this.wmGenericDao.findById(scheduledemployeeId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No ScheduledEmployee found with id: {}", scheduledemployeeId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public List<ScheduledEmployee> findByMultipleIds(List<Integer> scheduledemployeeIds, boolean orderedReturn) {
        LOGGER.debug("Finding ScheduledEmployees by ids: {}", scheduledemployeeIds);

        return this.wmGenericDao.findByMultipleIds(scheduledemployeeIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "when2workTransactionManager")
    @Override
    public ScheduledEmployee update(ScheduledEmployee scheduledEmployee) {
        LOGGER.debug("Updating ScheduledEmployee with information: {}", scheduledEmployee);

        this.wmGenericDao.update(scheduledEmployee);
        this.wmGenericDao.refresh(scheduledEmployee);

        return scheduledEmployee;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public ScheduledEmployee partialUpdate(Integer scheduledemployeeId, Map<String, Object>scheduledEmployeePatch) {
        LOGGER.debug("Partially Updating the ScheduledEmployee with id: {}", scheduledemployeeId);

        ScheduledEmployee scheduledEmployee = getById(scheduledemployeeId);

        try {
            ObjectReader scheduledEmployeeReader = WMObjectMapper.getInstance().reader().forType(ScheduledEmployee.class).withValueToUpdate(scheduledEmployee);
            scheduledEmployee = scheduledEmployeeReader.readValue(WMObjectMapper.getInstance().writeValueAsString(scheduledEmployeePatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", scheduledEmployeePatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        scheduledEmployee = update(scheduledEmployee);

        return scheduledEmployee;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public ScheduledEmployee delete(Integer scheduledemployeeId) {
        LOGGER.debug("Deleting ScheduledEmployee with id: {}", scheduledemployeeId);
        ScheduledEmployee deleted = this.wmGenericDao.findById(scheduledemployeeId);
        if (deleted == null) {
            LOGGER.debug("No ScheduledEmployee found with id: {}", scheduledemployeeId);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), ScheduledEmployee.class.getSimpleName(), scheduledemployeeId);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public void delete(ScheduledEmployee scheduledEmployee) {
        LOGGER.debug("Deleting ScheduledEmployee with {}", scheduledEmployee);
        this.wmGenericDao.delete(scheduledEmployee);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<ScheduledEmployee> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all ScheduledEmployees");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<ScheduledEmployee> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all ScheduledEmployees");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service when2work for table ScheduledEmployee to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service when2work for table ScheduledEmployee to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}
