/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import jakarta.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.when_to_work.when2work.ScheduledEmployee;

/**
 * Service object for domain model class {@link ScheduledEmployee}.
 */
public interface ScheduledEmployeeService {

    /**
     * Creates a new ScheduledEmployee. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on ScheduledEmployee if any.
     *
     * @param scheduledEmployee Details of the ScheduledEmployee to be created; value cannot be null.
     * @return The newly created ScheduledEmployee.
     */
    ScheduledEmployee create(@Valid ScheduledEmployee scheduledEmployee);


	/**
     * Returns ScheduledEmployee by given id if exists.
     *
     * @param scheduledemployeeId The id of the ScheduledEmployee to get; value cannot be null.
     * @return ScheduledEmployee associated with the given scheduledemployeeId.
	 * @throws EntityNotFoundException If no ScheduledEmployee is found.
     */
    ScheduledEmployee getById(Integer scheduledemployeeId);

    /**
     * Find and return the ScheduledEmployee by given id if exists, returns null otherwise.
     *
     * @param scheduledemployeeId The id of the ScheduledEmployee to get; value cannot be null.
     * @return ScheduledEmployee associated with the given scheduledemployeeId.
     */
    ScheduledEmployee findById(Integer scheduledemployeeId);

	/**
     * Find and return the list of ScheduledEmployees by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param scheduledemployeeIds The id's of the ScheduledEmployee to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return ScheduledEmployees associated with the given scheduledemployeeIds.
     */
    List<ScheduledEmployee> findByMultipleIds(List<Integer> scheduledemployeeIds, boolean orderedReturn);


    /**
     * Updates the details of an existing ScheduledEmployee. It replaces all fields of the existing ScheduledEmployee with the given scheduledEmployee.
     *
     * This method overrides the input field values using Server side or database managed properties defined on ScheduledEmployee if any.
     *
     * @param scheduledEmployee The details of the ScheduledEmployee to be updated; value cannot be null.
     * @return The updated ScheduledEmployee.
     * @throws EntityNotFoundException if no ScheduledEmployee is found with given input.
     */
    ScheduledEmployee update(@Valid ScheduledEmployee scheduledEmployee);


    /**
     * Partially updates the details of an existing ScheduledEmployee. It updates only the
     * fields of the existing ScheduledEmployee which are passed in the scheduledEmployeePatch.
     *
     * This method overrides the input field values using Server side or database managed properties defined on ScheduledEmployee if any.
     *
     * @param scheduledemployeeId The id of the ScheduledEmployee to be deleted; value cannot be null.
     * @param scheduledEmployeePatch The partial data of ScheduledEmployee which is supposed to be updated; value cannot be null.
     * @return The updated ScheduledEmployee.
     * @throws EntityNotFoundException if no ScheduledEmployee is found with given input.
     */
    ScheduledEmployee partialUpdate(Integer scheduledemployeeId, Map<String, Object> scheduledEmployeePatch);

    /**
     * Deletes an existing ScheduledEmployee with the given id.
     *
     * @param scheduledemployeeId The id of the ScheduledEmployee to be deleted; value cannot be null.
     * @return The deleted ScheduledEmployee.
     * @throws EntityNotFoundException if no ScheduledEmployee found with the given id.
     */
    ScheduledEmployee delete(Integer scheduledemployeeId);

    /**
     * Deletes an existing ScheduledEmployee with the given object.
     *
     * @param scheduledEmployee The instance of the ScheduledEmployee to be deleted; value cannot be null.
     */
    void delete(ScheduledEmployee scheduledEmployee);

    /**
     * Find all ScheduledEmployees matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching ScheduledEmployees.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<ScheduledEmployee> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all ScheduledEmployees matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching ScheduledEmployees.
     *
     * @see Pageable
     * @see Page
     */
    Page<ScheduledEmployee> findAll(String query, Pageable pageable);

    /**
     * Exports all ScheduledEmployees matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all ScheduledEmployees matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the ScheduledEmployees in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the ScheduledEmployee.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}
