/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import jakarta.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.when_to_work.when2work.Schedule;
import com.wavemaker.when_to_work.when2work.ScheduledEmployee;

/**
 * Service object for domain model class {@link Schedule}.
 */
public interface ScheduleService {

    /**
     * Creates a new Schedule. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Schedule if any.
     *
     * @param schedule Details of the Schedule to be created; value cannot be null.
     * @return The newly created Schedule.
     */
    Schedule create(@Valid Schedule schedule);


	/**
     * Returns Schedule by given id if exists.
     *
     * @param scheduleIdInstance The id of the Schedule to get; value cannot be null.
     * @return Schedule associated with the given scheduleIdInstance.
	 * @throws EntityNotFoundException If no Schedule is found.
     */
    Schedule getById(Integer scheduleIdInstance);

    /**
     * Find and return the Schedule by given id if exists, returns null otherwise.
     *
     * @param scheduleIdInstance The id of the Schedule to get; value cannot be null.
     * @return Schedule associated with the given scheduleIdInstance.
     */
    Schedule findById(Integer scheduleIdInstance);

	/**
     * Find and return the list of Schedules by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param scheduleIdInstances The id's of the Schedule to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return Schedules associated with the given scheduleIdInstances.
     */
    List<Schedule> findByMultipleIds(List<Integer> scheduleIdInstances, boolean orderedReturn);


    /**
     * Updates the details of an existing Schedule. It replaces all fields of the existing Schedule with the given schedule.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Schedule if any.
     *
     * @param schedule The details of the Schedule to be updated; value cannot be null.
     * @return The updated Schedule.
     * @throws EntityNotFoundException if no Schedule is found with given input.
     */
    Schedule update(@Valid Schedule schedule);


    /**
     * Partially updates the details of an existing Schedule. It updates only the
     * fields of the existing Schedule which are passed in the schedulePatch.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Schedule if any.
     *
     * @param scheduleIdInstance The id of the Schedule to be deleted; value cannot be null.
     * @param schedulePatch The partial data of Schedule which is supposed to be updated; value cannot be null.
     * @return The updated Schedule.
     * @throws EntityNotFoundException if no Schedule is found with given input.
     */
    Schedule partialUpdate(Integer scheduleIdInstance, Map<String, Object> schedulePatch);

    /**
     * Deletes an existing Schedule with the given id.
     *
     * @param scheduleIdInstance The id of the Schedule to be deleted; value cannot be null.
     * @return The deleted Schedule.
     * @throws EntityNotFoundException if no Schedule found with the given id.
     */
    Schedule delete(Integer scheduleIdInstance);

    /**
     * Deletes an existing Schedule with the given object.
     *
     * @param schedule The instance of the Schedule to be deleted; value cannot be null.
     */
    void delete(Schedule schedule);

    /**
     * Find all Schedules matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Schedules.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<Schedule> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all Schedules matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Schedules.
     *
     * @see Pageable
     * @see Page
     */
    Page<Schedule> findAll(String query, Pageable pageable);

    /**
     * Exports all Schedules matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all Schedules matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the Schedules in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the Schedule.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);

    /*
     * Returns the associated scheduledEmployees for given Schedule id.
     *
     * @param scheduleId value of scheduleId; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated ScheduledEmployee instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<ScheduledEmployee> findAssociatedScheduledEmployees(Integer scheduleId, Pageable pageable);

}
