/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Lazy;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.commons.WMObjectMapper;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.annotations.EntityService;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.when_to_work.when2work.GroupSkill;
import com.wavemaker.when_to_work.when2work.SkillGroup;


/**
 * ServiceImpl object for domain model class SkillGroup.
 *
 * @see SkillGroup
 */
@Service("when2work.SkillGroupService")
@Validated
@EntityService(entityClass = SkillGroup.class, serviceId = "when2work")
public class SkillGroupServiceImpl implements SkillGroupService {

    private static final Logger LOGGER = LoggerFactory.getLogger(SkillGroupServiceImpl.class);

    @Lazy
    @Autowired
    @Qualifier("when2work.GroupSkillService")
    private GroupSkillService groupSkillService;

    @Autowired
    @Qualifier("when2work.SkillGroupDao")
    private WMGenericDao<SkillGroup, Integer> wmGenericDao;


    public void setWMGenericDao(WMGenericDao<SkillGroup, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public SkillGroup create(SkillGroup skillGroup) {
        LOGGER.debug("Creating a new SkillGroup with information: {}", skillGroup);

        SkillGroup skillGroupCreated = this.wmGenericDao.create(skillGroup);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(skillGroupCreated);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public SkillGroup getById(Integer skillgroupId) {
        LOGGER.debug("Finding SkillGroup by id: {}", skillgroupId);
        return this.wmGenericDao.findById(skillgroupId);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public SkillGroup findById(Integer skillgroupId) {
        LOGGER.debug("Finding SkillGroup by id: {}", skillgroupId);
        try {
            return this.wmGenericDao.findById(skillgroupId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No SkillGroup found with id: {}", skillgroupId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public List<SkillGroup> findByMultipleIds(List<Integer> skillgroupIds, boolean orderedReturn) {
        LOGGER.debug("Finding SkillGroups by ids: {}", skillgroupIds);

        return this.wmGenericDao.findByMultipleIds(skillgroupIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "when2workTransactionManager")
    @Override
    public SkillGroup update(SkillGroup skillGroup) {
        LOGGER.debug("Updating SkillGroup with information: {}", skillGroup);

        this.wmGenericDao.update(skillGroup);
        this.wmGenericDao.refresh(skillGroup);

        return skillGroup;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public SkillGroup partialUpdate(Integer skillgroupId, Map<String, Object>skillGroupPatch) {
        LOGGER.debug("Partially Updating the SkillGroup with id: {}", skillgroupId);

        SkillGroup skillGroup = getById(skillgroupId);

        try {
            ObjectReader skillGroupReader = WMObjectMapper.getInstance().reader().forType(SkillGroup.class).withValueToUpdate(skillGroup);
            skillGroup = skillGroupReader.readValue(WMObjectMapper.getInstance().writeValueAsString(skillGroupPatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", skillGroupPatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        skillGroup = update(skillGroup);

        return skillGroup;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public SkillGroup delete(Integer skillgroupId) {
        LOGGER.debug("Deleting SkillGroup with id: {}", skillgroupId);
        SkillGroup deleted = this.wmGenericDao.findById(skillgroupId);
        if (deleted == null) {
            LOGGER.debug("No SkillGroup found with id: {}", skillgroupId);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), SkillGroup.class.getSimpleName(), skillgroupId);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "when2workTransactionManager")
    @Override
    public void delete(SkillGroup skillGroup) {
        LOGGER.debug("Deleting SkillGroup with {}", skillGroup);
        this.wmGenericDao.delete(skillGroup);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<SkillGroup> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all SkillGroups");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<SkillGroup> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all SkillGroups");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service when2work for table SkillGroup to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service when2work for table SkillGroup to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "when2workTransactionManager")
    @Override
    public Page<GroupSkill> findAssociatedGroupSkills(Integer groupId, Pageable pageable) {
        LOGGER.debug("Fetching all associated groupSkills");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("skillGroup.groupId = '" + groupId + "'");

        return groupSkillService.findAll(queryBuilder.toString(), pageable);
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service GroupSkillService instance
     */
    protected void setGroupSkillService(GroupSkillService service) {
        this.groupSkillService = service;
    }

}
