/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.when_to_work.when2work.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import jakarta.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.when_to_work.when2work.GroupSkill;
import com.wavemaker.when_to_work.when2work.SkillGroup;

/**
 * Service object for domain model class {@link SkillGroup}.
 */
public interface SkillGroupService {

    /**
     * Creates a new SkillGroup. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on SkillGroup if any.
     *
     * @param skillGroup Details of the SkillGroup to be created; value cannot be null.
     * @return The newly created SkillGroup.
     */
    SkillGroup create(@Valid SkillGroup skillGroup);


	/**
     * Returns SkillGroup by given id if exists.
     *
     * @param skillgroupId The id of the SkillGroup to get; value cannot be null.
     * @return SkillGroup associated with the given skillgroupId.
	 * @throws EntityNotFoundException If no SkillGroup is found.
     */
    SkillGroup getById(Integer skillgroupId);

    /**
     * Find and return the SkillGroup by given id if exists, returns null otherwise.
     *
     * @param skillgroupId The id of the SkillGroup to get; value cannot be null.
     * @return SkillGroup associated with the given skillgroupId.
     */
    SkillGroup findById(Integer skillgroupId);

	/**
     * Find and return the list of SkillGroups by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param skillgroupIds The id's of the SkillGroup to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return SkillGroups associated with the given skillgroupIds.
     */
    List<SkillGroup> findByMultipleIds(List<Integer> skillgroupIds, boolean orderedReturn);


    /**
     * Updates the details of an existing SkillGroup. It replaces all fields of the existing SkillGroup with the given skillGroup.
     *
     * This method overrides the input field values using Server side or database managed properties defined on SkillGroup if any.
     *
     * @param skillGroup The details of the SkillGroup to be updated; value cannot be null.
     * @return The updated SkillGroup.
     * @throws EntityNotFoundException if no SkillGroup is found with given input.
     */
    SkillGroup update(@Valid SkillGroup skillGroup);


    /**
     * Partially updates the details of an existing SkillGroup. It updates only the
     * fields of the existing SkillGroup which are passed in the skillGroupPatch.
     *
     * This method overrides the input field values using Server side or database managed properties defined on SkillGroup if any.
     *
     * @param skillgroupId The id of the SkillGroup to be deleted; value cannot be null.
     * @param skillGroupPatch The partial data of SkillGroup which is supposed to be updated; value cannot be null.
     * @return The updated SkillGroup.
     * @throws EntityNotFoundException if no SkillGroup is found with given input.
     */
    SkillGroup partialUpdate(Integer skillgroupId, Map<String, Object> skillGroupPatch);

    /**
     * Deletes an existing SkillGroup with the given id.
     *
     * @param skillgroupId The id of the SkillGroup to be deleted; value cannot be null.
     * @return The deleted SkillGroup.
     * @throws EntityNotFoundException if no SkillGroup found with the given id.
     */
    SkillGroup delete(Integer skillgroupId);

    /**
     * Deletes an existing SkillGroup with the given object.
     *
     * @param skillGroup The instance of the SkillGroup to be deleted; value cannot be null.
     */
    void delete(SkillGroup skillGroup);

    /**
     * Find all SkillGroups matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching SkillGroups.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<SkillGroup> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all SkillGroups matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching SkillGroups.
     *
     * @see Pageable
     * @see Page
     */
    Page<SkillGroup> findAll(String query, Pageable pageable);

    /**
     * Exports all SkillGroups matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all SkillGroups matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the SkillGroups in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the SkillGroup.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);

    /*
     * Returns the associated groupSkills for given SkillGroup id.
     *
     * @param groupId value of groupId; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated GroupSkill instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<GroupSkill> findAssociatedGroupSkills(Integer groupId, Pageable pageable);

}
