/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.when_to_work.getShiftDetails.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * RootResponse
 */

public class RootResponse {
  @JsonProperty("date")
  private String date = null;

  @JsonProperty("duration")
  private Integer duration = null;

  @JsonProperty("shiftId")
  private Integer shiftId = null;

  @JsonProperty("companyId")
  private Integer companyId = null;

  @JsonProperty("color")
  private String color = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("employeeId")
  private Integer employeeId = null;

  @JsonProperty("startTime")
  private String startTime = null;

  @JsonProperty("endTime")
  private String endTime = null;

  @JsonProperty("isOvernight")
  private Boolean isOvernight = null;

  @JsonProperty("position")
  private String position = null;

  @JsonProperty("category")
  private String category = null;

  public RootResponse date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public RootResponse duration(Integer duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  public Integer getDuration() {
    return duration;
  }

  public void setDuration(Integer duration) {
    this.duration = duration;
  }

  public RootResponse shiftId(Integer shiftId) {
    this.shiftId = shiftId;
    return this;
  }

   /**
   * Get shiftId
   * @return shiftId
  **/
  public Integer getShiftId() {
    return shiftId;
  }

  public void setShiftId(Integer shiftId) {
    this.shiftId = shiftId;
  }

  public RootResponse companyId(Integer companyId) {
    this.companyId = companyId;
    return this;
  }

   /**
   * Get companyId
   * @return companyId
  **/
  public Integer getCompanyId() {
    return companyId;
  }

  public void setCompanyId(Integer companyId) {
    this.companyId = companyId;
  }

  public RootResponse color(String color) {
    this.color = color;
    return this;
  }

   /**
   * Get color
   * @return color
  **/
  public String getColor() {
    return color;
  }

  public void setColor(String color) {
    this.color = color;
  }

  public RootResponse description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public RootResponse employeeId(Integer employeeId) {
    this.employeeId = employeeId;
    return this;
  }

   /**
   * Get employeeId
   * @return employeeId
  **/
  public Integer getEmployeeId() {
    return employeeId;
  }

  public void setEmployeeId(Integer employeeId) {
    this.employeeId = employeeId;
  }

  public RootResponse startTime(String startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  public String getStartTime() {
    return startTime;
  }

  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }

  public RootResponse endTime(String endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  public String getEndTime() {
    return endTime;
  }

  public void setEndTime(String endTime) {
    this.endTime = endTime;
  }

  public RootResponse isOvernight(Boolean isOvernight) {
    this.isOvernight = isOvernight;
    return this;
  }

   /**
   * Get isOvernight
   * @return isOvernight
  **/
  public Boolean isIsOvernight() {
    return isOvernight;
  }

  public void setIsOvernight(Boolean isOvernight) {
    this.isOvernight = isOvernight;
  }

  public RootResponse position(String position) {
    this.position = position;
    return this;
  }

   /**
   * Get position
   * @return position
  **/
  public String getPosition() {
    return position;
  }

  public void setPosition(String position) {
    this.position = position;
  }

  public RootResponse category(String category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootResponse RootResponse = (RootResponse) o;
    return Objects.equals(this.date, RootResponse.date) &&
        Objects.equals(this.duration, RootResponse.duration) &&
        Objects.equals(this.shiftId, RootResponse.shiftId) &&
        Objects.equals(this.companyId, RootResponse.companyId) &&
        Objects.equals(this.color, RootResponse.color) &&
        Objects.equals(this.description, RootResponse.description) &&
        Objects.equals(this.employeeId, RootResponse.employeeId) &&
        Objects.equals(this.startTime, RootResponse.startTime) &&
        Objects.equals(this.endTime, RootResponse.endTime) &&
        Objects.equals(this.isOvernight, RootResponse.isOvernight) &&
        Objects.equals(this.position, RootResponse.position) &&
        Objects.equals(this.category, RootResponse.category);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, duration, shiftId, companyId, color, description, employeeId, startTime, endTime, isOvernight, position, category);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootResponse {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    shiftId: ").append(toIndentedString(shiftId)).append("\n");
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    employeeId: ").append(toIndentedString(employeeId)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    isOvernight: ").append(toIndentedString(isOvernight)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
